# adduser
# Autogenerated from man page /usr/share/man/man8/adduser.8.gz
complete -c adduser -l badname -d 'Allow names that do not conform to standards'
complete -c adduser -s b -l base-dirBASE_DIR -d 'The default base directory for the system if -dHOME_DIR is not specified'
complete -c adduser -s c -l commentCOMMENT -d 'Any text string'
complete -c adduser -s d -l home-dirHOME_DIR -d 'The new user will be created using HOME_DIR as the value for the user\\*(Aqs l…'
complete -c adduser -s D -l defaults -d 'See below, the subsection "Changing the default values"'
complete -c adduser -s e -l expiredateEXPIRE_DATE -d 'The date on which the user account will be disabled'
complete -c adduser -s f -l inactiveINACTIVE -d 'defines the number of days after the password exceeded its maximum age where …'
complete -c adduser -s F -l add-subids-for-system -d 'Update /etc/subuid and /etc/subgid even when creating a system account with -…'
complete -c adduser -s g -l gidGROUP -d 'The name or the number of the user\\*(Aqs primary group'
complete -c adduser -s G -l groupsGROUP1 -d 'A list of supplementary groups which the user is also a member of'
complete -c adduser -s h -l help -d 'Display help message and exit'
complete -c adduser -s k -l skelSKEL_DIR -d 'The skeleton directory, which contains files and directories to be copied in …'
complete -c adduser -s K -l keyKEY -d 'Overrides /etc/login'
complete -c adduser -s l -l no-log-init -d 'Do not add the user to the lastlog and faillog databases'
complete -c adduser -s m -l create-home -d 'Create the user\\*(Aqs home directory if it does not exist'
complete -c adduser -s M -l no-create-home -d 'Do not create the user\\*(Aqs home directory, even if the system wide setting …'
complete -c adduser -s N -l no-user-group -d 'Do not create a group with the same name as the user, but add the user to the…'
complete -c adduser -s o -l non-unique -d 'allows the creation of an account with an already existing UID'
complete -c adduser -s p -l passwordPASSWORD -d 'defines an initial password for the account'
complete -c adduser -s r -l system -d 'Create a system account'
complete -c adduser -s R -l rootCHROOT_DIR -d 'Apply changes in the CHROOT_DIR directory and use the configuration files fro…'
complete -c adduser -s P -l prefixPREFIX_DIR -d 'Apply changes to configuration files under the root filesystem found under th…'
complete -c adduser -s s -l shellSHELL -d 'sets the path to the user\\*(Aqs login shell'
complete -c adduser -s u -l uidUID -d 'The numerical value of the user\\*(Aqs ID'
complete -c adduser -s U -l user-group -d 'Create a group with the same name as the user, and add the user to this group'
complete -c adduser -s Z -l selinux-userSEUSER -d 'defines the SELinux user for the new account'
complete -c adduser -l selinux-rangeSERANGE -d 'defines the SELinux MLS range for the new account'
complete -c adduser -l base-dir
complete -c adduser -l comment
complete -c adduser -l home-dir
complete -c adduser -l expiredate
complete -c adduser -l inactive
complete -c adduser -l gid
complete -c adduser -o U/--user-group -d 'is specified on the command line), a group will be created for the user, with…'
complete -c adduser -o N/--no-user-group -d 'is specified on the command line), useradd will set the primary group of the …'
complete -c adduser -l groups
complete -c adduser -l skel
complete -c adduser -l key
complete -c adduser -s 1 -d 'can be used when creating an account to turn off password aging.  Multiple'
complete -c adduser -l password
complete -c adduser -l root
complete -c adduser -l prefix
complete -c adduser -l shell
complete -c adduser -l uid
complete -c adduser -l selinux-user
complete -c adduser -l selinux-range

