# alacritty
# Autogenerated from man page /usr/share/man/man1/alacritty.1.gz
complete -c alacritty -l class -d 'Defines the window class hint on Linux'
complete -c alacritty -s e -l command -d 'Command and args to execute (must be last argument)'
complete -c alacritty -l config-file -d 'Specify alternative configuration file'
complete -c alacritty -s o -l option -d 'Override configuration file options'
complete -c alacritty -l socket -d 'Path for IPC socket creation'
complete -c alacritty -s T -l title -d 'Defines the window title'

