# applydeltarpm
# Autogenerated from man page /usr/share/man/man8/applydeltarpm.8.gz
complete -c applydeltarpm -s r -d 'option, if no rpm name is provided on-disk data is used.  You can use'
complete -c applydeltarpm -s p -d 'to make applydeltarpm print the percentage of completion, or'
complete -c applydeltarpm -s v -d 'to make it more verbose about its operation'
complete -c applydeltarpm -s c -d 'option selects full (i. e.  slow) on-disk checking, whereas'
complete -c applydeltarpm -s C -d 'only checks if the filesizes have not changed'
complete -c applydeltarpm -s s -d 'sequence option'
complete -c applydeltarpm -s i -d option

