# apropos.man-db
# Autogenerated from man page /usr/share/man/man1/apropos.man-db.1.gz
complete -c 'apropos.man-db' -s d -l debug -d 'Print debugging information'
complete -c 'apropos.man-db' -s v -l verbose -d 'Print verbose warning messages'
complete -c 'apropos.man-db' -s r -l regex -d 'Interpret each keyword as a regular expression'
complete -c 'apropos.man-db' -s w -l wildcard -d 'Interpret each keyword as a pattern containing shell style wildcards'
complete -c 'apropos.man-db' -s e -l exact -d 'Each keyword will be exactly matched against the page names and the descripti…'
complete -c 'apropos.man-db' -s a -l and -d 'Only display items that match all the supplied keywords'
complete -c 'apropos.man-db' -s l -l long -d 'Do not trim output to the terminal width'
complete -c 'apropos.man-db' -s s -d '--sections=list\\/, \\ --section=list Search only the given manual sections'
complete -c 'apropos.man-db' -s m -d '--systems=system\\|[\\|,. \\|. \\|'
complete -c 'apropos.man-db' -s M -l manpath -d 'Specify an alternate set of colon-delimited manual page hierarchies to search'
complete -c 'apropos.man-db' -s L -l locale -d 'apropos will normally determine your current locale by a call to the C functi…'
complete -c 'apropos.man-db' -s C -l config-file -d 'Use this user configuration file rather than the default of R ~/. manpath '
complete -c 'apropos.man-db' -s '?' -l help -d 'Print a help message and exit'
complete -c 'apropos.man-db' -l usage -d 'Print a short usage message and exit'
complete -c 'apropos.man-db' -l sections
complete -c 'apropos.man-db' -l section -d 'Search only the given manual sections'
complete -c 'apropos.man-db' -l systems -d 'If this system has access to other operating systems\' manual page description…'
complete -c 'apropos.man-db' -s V -l version -d 'Display version information.  EXIT STATUS'

