# authselect
# Autogenerated from man page /usr/share/man/man8/authselect.8.gz
complete -c authselect -l force -s f
complete -c authselect -l nobackup -d 'option is set'
complete -c authselect -s b
complete -c authselect -l backup
complete -c authselect -l quiet -s q
complete -c authselect -l raw -d 'option is specified, the command will print raw parameters as they were passe…'
complete -c authselect -s a -l all
complete -c authselect -s n -l nsswitch
complete -c authselect -s s -l system-auth
complete -c authselect -s p -l password-auth
complete -c authselect -s c -l smartcard-auth
complete -c authselect -l fingerprint-auth
complete -c authselect -s o -l postlogin
complete -c authselect -s d -l dconf-db
complete -c authselect -s l -l dconf-lock
complete -c authselect -l vendor -s v
complete -c authselect -l base-on
complete -c authselect -l base-on-default
complete -c authselect -l symlink-meta
complete -c authselect -l symlink-nsswitch
complete -c authselect -l symlink-pam
complete -c authselect -l symlink-dconf
complete -c authselect -l symlink
complete -c authselect -l debug
complete -c authselect -l trace
complete -c authselect -l warn

