# avcstat
# Autogenerated from man page /usr/share/man/man8/avcstat.8.gz
complete -c avcstat -s c -d 'Display the cumulative values'
complete -c avcstat -s f -d 'Specifies the location of the AVC statistics file, defaulting to /sys/fs/seli…'

