# bluetoothctl
# Autogenerated from man page /usr/share/man/man1/bluetoothctl.1.gz
complete -c bluetoothctl -s a -l agent -d 'Register agent handler: <capability>'
complete -c bluetoothctl -s e -l endpoints -d 'Register Media endpoints'
complete -c bluetoothctl -s m -l monitor -d 'Enable monitor output'
complete -c bluetoothctl -s t -l timeout -d 'Timeout in seconds for non-interactive mode'
complete -c bluetoothctl -s v -l version -d 'Display version'
complete -c bluetoothctl -s h -l help -d 'Display help'

