# booleans
# Autogenerated from man page /usr/share/man/man8/booleans.8.gz
complete -c booleans -s P -d 'to make the setting persistent across reboots'
complete -c booleans -s b -d option
complete -c booleans -s a -d option

