# btmgmt
# Autogenerated from man page /usr/share/man/man1/btmgmt.1.gz
complete -c btmgmt -o i/--index -d 'Specify adapter index'
complete -c btmgmt -o m-/-monitor -d 'Enable monitor output'
complete -c btmgmt -o t/--timeout -d 'Timeout in seconds for non-interactive mode'
complete -c btmgmt -o v/--version -d 'Display version'
complete -c btmgmt -o i/--init-script -d 'Init script file'
complete -c btmgmt -o h/--help -d 'Display help'

