# btrfs-quota
# Autogenerated from man page /usr/share/man/man8/btrfs-quota.8.gz
complete -c btrfs-quota -s s -l simple -d 'use simple quotas (squotas) instead of full qgroup accounting rescan [options…'
complete -c btrfs-quota -l status -d 'show status of a running rescan operation'
complete -c btrfs-quota -s w -l wait -d 'start rescan and wait for it to finish (can be already in progress)'
complete -c btrfs-quota -s W -l wait-norescan -d 'wait for rescan to finish without starting it EXIT STATUS'

