# btrfs
# Autogenerated from man page /usr/share/man/man8/btrfs.8.gz
complete -c btrfs -l format -d 'if supported by the command, print subcommand output in that format (text, js…'
complete -c btrfs -s v -l verbose -d 'increase verbosity of the subcommand'
complete -c btrfs -s q -l quiet -d 'print only errors'
complete -c btrfs -l log -d 'set log level (default, info, verbose, debug, quiet) The remaining options ar…'
complete -c btrfs -l help -d 'print condensed help for all subcommands'
complete -c btrfs -l version -d 'print version string'

