# chronyc
# Autogenerated from man page /usr/share/man/man1/chronyc.1.gz
complete -c chronyc -s 4
complete -c chronyc -s 6
complete -c chronyc -s n
complete -c chronyc -s N
complete -c chronyc -s c
complete -c chronyc -s e
complete -c chronyc -s d
complete -c chronyc -s m
complete -c chronyc -s h
complete -c chronyc -s p
complete -c chronyc -s f
complete -c chronyc -s a
complete -c chronyc -s v -l version
complete -c chronyc -l help

