# chronyd
# Autogenerated from man page /usr/share/man/man8/chronyd.8.gz
complete -c chronyd -s 4
complete -c chronyd -s 6
complete -c chronyd -s f
complete -c chronyd -s n
complete -c chronyd -s d
complete -c chronyd -s l
complete -c chronyd -s L
complete -c chronyd -s p
complete -c chronyd -s q
complete -c chronyd -s Q
complete -c chronyd -s r
complete -c chronyd -s R
complete -c chronyd -s s
complete -c chronyd -s t
complete -c chronyd -s u
complete -c chronyd -s U
complete -c chronyd -s F
complete -c chronyd -s P
complete -c chronyd -s m
complete -c chronyd -s x
complete -c chronyd -s v -l version
complete -c chronyd -s h -l help

