# combinedeltarpm
# Autogenerated from man page /usr/share/man/man8/combinedeltarpm.8.gz
complete -c combinedeltarpm -s v -d 'option to make combinedeltarpm more verbose about its work'
complete -c combinedeltarpm -s V -d 'option to specify a different version if desired.  The'
complete -c combinedeltarpm -s z -d 'option can be used to specify a different compression method, the default is …'
complete -c combinedeltarpm -s S -d 'option which will be used as signature reference'

