# dnf-changelog
# Autogenerated from man page /usr/share/man/man8/dnf-changelog.8.gz
complete -c dnf-changelog -l since -d 'Show only changelog entries since <date>'
complete -c dnf-changelog -l count -d 'Show maximum of <number> changelog entries per package'
complete -c dnf-changelog -l upgrades -d 'Show only new changelog entries for packages, that provide an upgrade for som…'

