# dnf-offline-upgrade
# Autogenerated from man page /usr/share/man/man8/dnf-offline-upgrade.8.gz
complete -c dnf-offline-upgrade -l releasever -d 'REQUIRED.  The version to upgrade to.  Sets $releasever in all enabled repos'
complete -c dnf-offline-upgrade -l downloaddir -d 'Redirect download of packages to provided <path>'
complete -c dnf-offline-upgrade -l distro-sync -d 'Behave like dnf distro-sync: always install packages from the new release, ev…'
complete -c dnf-offline-upgrade -l no-downgrade -d 'Behave like dnf update: do not install packages from the new release if they …'
complete -c dnf-offline-upgrade -l poweroff -d 'When applied with the reboot subcommand, the system will power off after upgr…'
complete -c dnf-offline-upgrade -l number -d 'Applied with log subcommand will show the log specified by the number'

