# dnf-needs-restarting
# Autogenerated from man page /usr/share/man/man8/dnf-needs-restarting.8.gz
complete -c dnf-needs-restarting -s u -l useronly -d 'Only consider processes belonging to the running user'
complete -c dnf-needs-restarting -s r -l reboothint -d 'Only report whether a reboot is required (exit code 1) or not (exit code 0)'
complete -c dnf-needs-restarting -s s -l services -d 'Only list the affected systemd services'

