# dnf-download
# Autogenerated from man page /usr/share/man/man8/dnf-download.8.gz
complete -c dnf-download -l help-cmd -d 'Show this help'
complete -c dnf-download -l arch -d 'Limit the query to packages of given architectures (default is all compatible…'
complete -c dnf-download -l source -d 'Download the source rpm'
complete -c dnf-download -l debuginfo -d 'Download the debuginfo rpm'
complete -c dnf-download -l downloaddir -d 'Download directory, default is the current directory (the directory must exis…'
complete -c dnf-download -l url -d 'Instead of downloading, print list of urls where the rpms can be downloaded'
complete -c dnf-download -l urlprotocol -d 'Limit the protocol of the urls output by the --url option'
complete -c dnf-download -l resolve -d 'Resolves dependencies of specified packages and downloads missing dependencie…'
complete -c dnf-download -l alldeps -d 'When used with --resolve, download all dependencies (do not skip already inst…'
complete -c dnf-download -l forcearch

