# dnf-debug
# Autogenerated from man page /usr/share/man/man8/dnf-debug.8.gz
complete -c dnf-debug -l norepos -d 'Do not dump content of enabled repos'
complete -c dnf-debug -l filter-types -d 'Limit package changes to specified type'
complete -c dnf-debug -l ignore-arch -d 'When installing package ignore architecture and install missing packages matc…'
complete -c dnf-debug -l install-latest -d 'When installing use the latest package of the same name and architecture'
complete -c dnf-debug -l output -d 'Only output list of packages which will be installed or removed'
complete -c dnf-debug -l remove-installonly -d 'Allow removal of install-only packages'

