# dnf-repoclosure
# Autogenerated from man page /usr/share/man/man8/dnf-repoclosure.8.gz
complete -c dnf-repoclosure -l arch -d 'Query only packages for specified architecture, can be specified multiple tim…'
complete -c dnf-repoclosure -l best -d 'Check only the newest packages per arch'
complete -c dnf-repoclosure -l check -d 'Specify repo ids to check, can be specified multiple times (default is all en…'
complete -c dnf-repoclosure -l newest -d 'Check only the newest packages in the repos'
complete -c dnf-repoclosure -l pkg -d 'Check closure for this package only'
complete -c dnf-repoclosure -l repo -d 'Specify repo ids to query, can be specified multiple times (default is all en…'

