# dnf-repomanage
# Autogenerated from man page /usr/share/man/man8/dnf-repomanage.8.gz
complete -c dnf-repomanage -l old -d 'Show older packages (for a package or a stream show all versions except the n…'
complete -c dnf-repomanage -l oldonly -d 'Show older packages (same as --old, but exclude the newest packages even when…'
complete -c dnf-repomanage -l new -d 'Show newest packages. UNINDENT '
complete -c dnf-repomanage -s s -l space -d 'Print resulting set separated by space instead of newline'
complete -c dnf-repomanage -s k -l keep -d 'Limit the resulting set to newest <keep-number> packages'

