# dnf-groups-manager
# Autogenerated from man page /usr/share/man/man8/dnf-groups-manager.8.gz
complete -c dnf-groups-manager -l load -d 'Load the groups metadata information from the specified file before performin…'
complete -c dnf-groups-manager -l save -d 'Save the result to this file'
complete -c dnf-groups-manager -l merge -d 'This is the same as loading and saving a file, however the "merge" file is lo…'
complete -c dnf-groups-manager -l print -d 'Also print the result to stdout'
complete -c dnf-groups-manager -l id -d 'The id to lookup/use for the group'
complete -c dnf-groups-manager -s n -l name -d 'The name to lookup/use for the group'
complete -c dnf-groups-manager -l description -d 'The description to use for the group'
complete -c dnf-groups-manager -l display-order -d 'Change the integer which controls the order groups are presented in, for exam…'
complete -c dnf-groups-manager -l translated-name -d 'A translation of the group name in the given language'
complete -c dnf-groups-manager -l translated-description -d 'A translation of the group description in the given language'
complete -c dnf-groups-manager -l user-visible -d 'Make the group visible in dnf grouplist (this is the default)'
complete -c dnf-groups-manager -l not-user-visible -d 'Make the group not visible in dnf grouplist'
complete -c dnf-groups-manager -l mandatory -d 'Store the package names specified within the mandatory section of the specifi…'
complete -c dnf-groups-manager -l optional -d 'Store the package names specified within the optional section of the specifie…'
complete -c dnf-groups-manager -l remove -d 'Instead of adding packages remove them'
complete -c dnf-groups-manager -l dependencies -d 'Also include the names of the direct dependencies for each package specified'

