# dnf-builddep
# Autogenerated from man page /usr/share/man/man8/dnf-builddep.8.gz
complete -c dnf-builddep -l help-cmd -d 'Show this help'
complete -c dnf-builddep -s D -l define -d 'Define the RPM macro named macro to the value expr when parsing spec files'
complete -c dnf-builddep -l spec -d 'Treat arguments as . spec files'
complete -c dnf-builddep -l srpm -d 'Treat arguments as source rpm files'
complete -c dnf-builddep -l skip-unavailable -d 'Skip build dependencies not available in repositories'

