# dnf-repograph
# Autogenerated from man page /usr/share/man/man8/dnf-repograph.8.gz
complete -c dnf-repograph -l repo -d 'Specify repo ids to query, can be specified multiple times (default is all en…'

