# dnf-reposync
# Autogenerated from man page /usr/share/man/man8/dnf-reposync.8.gz
complete -c dnf-reposync -s a -l arch -d 'Download only packages of given architectures (default is all architectures)'
complete -c dnf-reposync -l delete -d 'Delete local packages no longer present in repository'
complete -c dnf-reposync -l download-metadata -d 'Download all repository metadata'
complete -c dnf-reposync -s g -l gpgcheck -d 'Remove packages that fail GPG signature checking after downloading'
complete -c dnf-reposync -s m -l downloadcomps -d 'Also download and uncompress comps. xml'
complete -c dnf-reposync -l metadata-path -d 'Root path under which the downloaded metadata are stored'
complete -c dnf-reposync -s n -l newest-only -d 'Download only newest packages per-repo'
complete -c dnf-reposync -l norepopath -d 'Don\'t add the reponame to the download path'
complete -c dnf-reposync -s p -l download-path -d 'Root path under which the downloaded repositories are stored, relative to the…'
complete -c dnf-reposync -l safe-write-path -d 'Specify the filesystem path prefix under which the reposync is allowed to wri…'
complete -c dnf-reposync -l remote-time -d 'Try to set the timestamps of the downloaded files to those on the remote side'
complete -c dnf-reposync -l source -d 'Download only source packages'
complete -c dnf-reposync -s u -l urls -d 'Just print urls of what would be downloaded, don\'t download'

