# evmctl
# Autogenerated from man page /usr/share/man/man1/evmctl.1.gz
complete -c evmctl -l version -d 'help <command> import  [--rsa (deprecated)] pubkey keyring sign [-r] [--imaha…'
complete -c evmctl -s a -l hashalgo
complete -c evmctl -s s -l imasig -d '    --veritysig    sign an fs-verity file digest hash'
complete -c evmctl -s d -l imahash
complete -c evmctl -s f -l sigfile -d '    --xattr-user   store xattrs in user namespace (for testing purposes)     …'
complete -c evmctl -s k -l key -d '                   or a pkcs11 URI     --keyid n      overwrite signature key…'
complete -c evmctl -s o -l portable
complete -c evmctl -s p -l pass
complete -c evmctl -s r -l recursive
complete -c evmctl -s t -l type -d '                   x - skip fixing if both ima and evm xattrs exist (use with…'
complete -c evmctl -s n
complete -c evmctl -s u -l uuid -d '    --smack        use extra SMACK xattrs for EVM     --m32          force EV…'
complete -c evmctl -s v
complete -c evmctl -s h -l help -d 'Environment variables:'

