# exfat2img
# Autogenerated from man page /usr/share/man/man8/exfat2img.8.gz
complete -c exfat2img -o o--output -d 'Specify output result file'
complete -c exfat2img -s o -l output -d 'Specify output result file'
complete -c exfat2img -s V -d 'Prints the version number and exits'

