# exfatlabel
# Autogenerated from man page /usr/share/man/man8/exfatlabel.8.gz
complete -c exfatlabel -o i--volume-serial -d 'Switch to volume serial mode'
complete -c exfatlabel -s i -l volume-serial -d 'Switch to volume serial mode'
complete -c exfatlabel -s V -d 'Prints the version number and exits'

