# fdformat
# Autogenerated from man page /usr/share/man/man8/fdformat.8.gz
complete -c fdformat -s f -l from
complete -c fdformat -s t -l to
complete -c fdformat -s r -l repair
complete -c fdformat -s n -l no-verify
complete -c fdformat -s h -l help
complete -c fdformat -s V -l version

