# fips-finish-install
# Autogenerated from man page /usr/share/man/man8/fips-finish-install.8.gz
complete -c fips-finish-install -l complete -s f
complete -c fips-finish-install -l undo -d 'SEE ALSO'

