# fips-mode-setup
# Autogenerated from man page /usr/share/man/man8/fips-mode-setup.8.gz
complete -c fips-mode-setup -l enable -d 'oc o 2. 3'
complete -c fips-mode-setup -l disable -d 'oc o 2. 3'
complete -c fips-mode-setup -l check -l is-enabled -d 'oc o 2. 3'
complete -c fips-mode-setup -l no-bootcfg

