# fixfiles
# Autogenerated from man page /usr/share/man/man8/fixfiles.8.gz
complete -c fixfiles -s B -d 'If specified with onboot, this fixfiles will record the current date in the /'
complete -c fixfiles -s F -d 'Force reset of context to match file_context for customizable files'
complete -c fixfiles -s f -d 'Clear /tmp directory with out prompt for removal'
complete -c fixfiles -s R -d 'Use the rpm database to discover all files within the specified packages and …'
complete -c fixfiles -s C -d 'Run a diff on  the PREVIOUS_FILECONTEXT file to the currently installed one, …'
complete -c fixfiles -s N -d 'Only act on files created after the specified date'
complete -c fixfiles -s M -d 'Bind mount filesystems before relabeling them, this allows fixing the context…'
complete -c fixfiles -s v -d 'Modify verbosity from progress to verbose'

