# fuse2fs
# Autogenerated from man page /usr/share/man/man1/fuse2fs.1.gz
complete -c fuse2fs -s o -d 'mount options'
complete -c fuse2fs -s h -l help -d 'print help'
complete -c fuse2fs -s V -l version -d 'print version . SS "fuse2fs options:"'
complete -c fuse2fs -s d -d 'enable debug output (implies -f)'
complete -c fuse2fs -s f -d 'foreground operation'
complete -c fuse2fs -s s -d 'disable multi-threaded operation'

