# gpgv2
# Autogenerated from man page /usr/share/man/man1/gpgv2.1.gz
complete -c gpgv2 -l verbose -d 'TQ   -v Gives more information during processing'
complete -c gpgv2 -l quiet -d 'TQ   -q Try to be as quiet as possible'
complete -c gpgv2 -l keyring -d 'Add file to the list of keyrings'
complete -c gpgv2 -l output -d 'TQ   -o file Write output to file; to write to stdout use -'
complete -c gpgv2 -l status-fd -d 'Write special status strings to the file descriptor n'
complete -c gpgv2 -l logger-fd -d 'Write log output to file descriptor n and not to stderr'
complete -c gpgv2 -l log-file -d 'Same as --logger-fd, except the logger data is written to file file'
complete -c gpgv2 -l ignore-time-conflict -d 'GnuPG normally checks that the timestamps associated with keys and signatures…'
complete -c gpgv2 -l homedir -d 'Set the name of the home directory to dir'
complete -c gpgv2 -l weak-digest -d 'Treat the specified digest algorithm as weak'
complete -c gpgv2 -s v -d 'Gives more information during processing'
complete -c gpgv2 -s q -d 'Try to be as quiet as possible'
complete -c gpgv2 -s o -d 'Write output to file; to write to stdout use -'
complete -c gpgv2 -l enable-special-filenames -d 'This option enables a mode in which filenames of the form `-&n\', where n is a…'

