# grub2-emu
# Autogenerated from man page /usr/share/man/man1/grub2-emu.1.gz
complete -c grub2-emu -s d -l directory -d 'use GRUB files in the directory DIR [default=/boot/grub2]'
complete -c grub2-emu -s H -l hold -d 'wait until a debugger will attach'
complete -c grub2-emu -l memdisk -d 'use FILE as memdisk'
complete -c grub2-emu -s m -l device-map -d 'use FILE as the device map [default=/boot/grub2/device. map]'
complete -c grub2-emu -s r -l root -d 'Set root device'
complete -c grub2-emu -s v -l verbose -d 'print verbose messages'
complete -c grub2-emu -s W -l switch-root -d 'use switch-root to only switch root filesystem without restarting the kernel'
complete -c grub2-emu -s X -l kexec -d 'use kexec to boot Linux kernels via systemctl (pass twice to enable dangerous…'
complete -c grub2-emu -s '?' -l help -d 'give this help list'
complete -c grub2-emu -l usage -d 'give a short usage message'
complete -c grub2-emu -s V -l version -d 'print program version'

