# grub2-mkconfig
# Autogenerated from man page /usr/share/man/man8/grub2-mkconfig.8.gz
complete -c grub2-mkconfig -s o -l output -d 'output generated config to FILE [default=stdout]'
complete -c grub2-mkconfig -l no-grubenv-update -d 'do not update variables in the grubenv file'
complete -c grub2-mkconfig -s h -l help -d 'print this message and exit'
complete -c grub2-mkconfig -s V -l version -d 'print the version information and exit REPORTING BUGS Report bugs to <bug-gru…'

