# grub2-probe
# Autogenerated from man page /usr/share/man/man8/grub2-probe.8.gz
complete -c grub2-probe -s 0 -d 'separate items in output using ASCII NUL characters'
complete -c grub2-probe -s d -l device -d 'given argument is a system device, not a path'
complete -c grub2-probe -s m -l device-map -d 'use FILE as the device map [default=/boot/grub2/device. map]'
complete -c grub2-probe -s t -l target -d 'print TARGET available targets: abstraction, arc_hints, baremetal_hints, bios…'
complete -c grub2-probe -s v -l verbose -d 'print verbose messages (pass twice to enable debug printing)'
complete -c grub2-probe -s '?' -l help -d 'give this help list'
complete -c grub2-probe -l usage -d 'give a short usage message'
complete -c grub2-probe -s V -l version -d 'print program version'

