# grub2-script-check
# Autogenerated from man page /usr/share/man/man1/grub2-script-check.1.gz
complete -c grub2-script-check -s v -l verbose -d 'print verbose messages'
complete -c grub2-script-check -s '?' -l help -d 'give this help list'
complete -c grub2-script-check -l usage -d 'give a short usage message'
complete -c grub2-script-check -s V -l version -d 'print program version REPORTING BUGS Report bugs to <bug-grub@gnu. org>'

