# grub2-mklayout
# Autogenerated from man page /usr/share/man/man1/grub2-mklayout.1.gz
complete -c grub2-mklayout -s i -l input -d 'set input filename.  Default is STDIN'
complete -c grub2-mklayout -s o -l output -d 'set output filename.  Default is STDOUT'
complete -c grub2-mklayout -s v -l verbose -d 'print verbose messages'
complete -c grub2-mklayout -s '?' -l help -d 'give this help list'
complete -c grub2-mklayout -l usage -d 'give a short usage message'
complete -c grub2-mklayout -s V -l version -d 'print program version'

