# grub2-reboot
# Autogenerated from man page /usr/share/man/man8/grub2-reboot.8.gz
complete -c grub2-reboot -s h -l help -d 'print this message and exit'
complete -c grub2-reboot -s V -l version -d 'print the version information and exit'
complete -c grub2-reboot -l boot-directory -d 'expect GRUB images under the directory DIR/grub2 instead of the ,/boot/grub2/…'

