# grub2-switch-to-blscfg
# Autogenerated from man page /usr/share/man/man8/grub2-switch-to-blscfg.8.gz
complete -c grub2-switch-to-blscfg -s h -l help -d 'print this message and exit'
complete -c grub2-switch-to-blscfg -s V -l version -d 'print the version information and exit'
complete -c grub2-switch-to-blscfg -l backup-suffix -d bak
complete -c grub2-switch-to-blscfg -l bls-directory -d '\\,/boot/loader/entries\\/'
complete -c grub2-switch-to-blscfg -l config-file -d '\\,/etc/grub2-efi. cfg\\/'
complete -c grub2-switch-to-blscfg -l grub-defaults -d '\\,/etc/default/grub\\/'
complete -c grub2-switch-to-blscfg -l grub-directory -d '/boot/efi/EFI/fedora/ SEE ALSO The full documentation for grub-switch-to-blsc…'

