# grub2-set-password
# Autogenerated from man page /usr/share/man/man8/grub2-set-password.8.gz
complete -c grub2-set-password -s h -l help -d 'print this message and exit'
complete -c grub2-set-password -s v -l version -d 'print the version information and exit'
complete -c grub2-set-password -s o -l output_path -d 'put user'

