# ifenslave
# Autogenerated from man page /usr/share/man/man8/ifenslave.8.gz
complete -c ifenslave -s a -d 'Show information about all interfaces'
complete -c ifenslave -s c -d 'Change active slave'
complete -c ifenslave -s d -d 'Removes slave interfaces from the bonding device'
complete -c ifenslave -s f -d 'Force actions to be taken if one of the specified interfaces appears not to b…'
complete -c ifenslave -s h -d 'Display a help message and exit'
complete -c ifenslave -s u -d 'Show usage information and exit'
complete -c ifenslave -s v -d 'Print warning and debug messages'
complete -c ifenslave -s V -d 'Show version information and exit'

