# ipset
# Autogenerated from man page /usr/share/man/man8/ipset.8.gz
complete -c ipset -o exist -d 'Ignore errors when exactly the same set is to be created or already added ent…'
complete -c ipset -s o -o output -d 'Select the output format to the list command'
complete -c ipset -s q -o quiet -d 'Suppress any output to stdout and stderr'
complete -c ipset -s r -o resolve -d 'When listing sets, enforce name lookup'
complete -c ipset -s s -o sorted -d 'Sorted output.  When listing or saving sets, the entries are listed sorted'
complete -c ipset -s n -o name -d 'List just the names of the existing sets, i. e'
complete -c ipset -s t -o terse -d 'List the set names and headers, i. e.  suppress listing of set members'

