# kpartx
# Autogenerated from man page /usr/share/man/man8/kpartx.8.gz
complete -c kpartx -s a -d 'Add partition mappings'
complete -c kpartx -s d -d 'Delete partition mappings'
complete -c kpartx -s u -d 'Update partition mappings'
complete -c kpartx -s l -d 'List partition mappings that would be added -a'
complete -c kpartx -s r -d 'Read-only partition mappings'
complete -c kpartx -s p -d 'Set device name-partition number delimiter'
complete -c kpartx -s f -d 'Force creation of mappings; overrides \'no_partitions\' feature'
complete -c kpartx -s g -d 'Force GUID partition table (GPT)'
complete -c kpartx -s s -d 'Sync mode (Default).  Don\'t return until the partitions are created'
complete -c kpartx -s n -d 'Nosync mode.  Return before the partitions are created'
complete -c kpartx -s v -d 'Operate verbosely'

