# lchage
# Autogenerated from man page /usr/share/man/man1/lchage.1.gz
complete -c lchage -s d -l date -d 'Set the date of last password change to days after Jan 1 1970'
complete -c lchage -s E -l expire -d 'Set the account expiration date to days after Jan 1 1970'
complete -c lchage -s i -l interactive -d 'Ask all questions when connecting to the user database, even if default answe…'
complete -c lchage -s I -l inactive -d 'Disable the account after days after password expires (after the user is requ…'
complete -c lchage -s l -l list -d 'Only list current user\'s policy and make no changes'
complete -c lchage -s m -l mindays -d 'Require at least days days between password changes'
complete -c lchage -s M -l maxdays -d 'Require changing the password after days since last password change'
complete -c lchage -s W -l warndays -d 'Start warning the user days before password expires (before the user is requi…'

