# ldconfig
# Autogenerated from man page /usr/share/man/man8/ldconfig.8.gz
complete -c ldconfig -o 'c\\~' -d 'TQ  --format= fmt (Since glibc 2. 2) '
complete -c ldconfig -o 'C\\~' -d 'Use  cache instead of R /etc/ld. so. cache '
complete -c ldconfig -o 'f\\~' -d 'Use  conf instead of R /etc/ld. so. conf '
complete -c ldconfig -s i -d 'TQ  --ignore-aux-cache (Since glibc 2. 7) '
complete -c ldconfig -s l -d '(Since glibc 2'
complete -c ldconfig -s n -d 'Process only the directories specified on the command line; don\'t process the…'
complete -c ldconfig -s N -d 'Don\'t rebuild the cache'
complete -c ldconfig -s p -d 'TQ  --print-cache Print the lists of directories and candidate libraries stor…'
complete -c ldconfig -o 'r\\~' -d 'Change to and use  root as the root directory'
complete -c ldconfig -s v -d 'TQ  --verbose Verbose mode'
complete -c ldconfig -s V -d 'TQ  --version Print program version'
complete -c ldconfig -s c
complete -c ldconfig -l format -d '(Since glibc 2. 2)'
complete -c ldconfig -s C -d 'Use cache instead of /etc/ld. so. cache '
complete -c ldconfig -s f -d 'Use conf instead of /etc/ld. so. conf '
complete -c ldconfig -l ignore-aux-cache -d '(Since glibc 2. 7)'
complete -c ldconfig -s X -d 'is also specified, links are still updated'
complete -c ldconfig -l print-cache -d 'Print the lists of directories and candidate libraries stored in the current …'
complete -c ldconfig -s r -d 'Change to and use root as the root directory'
complete -c ldconfig -l verbose -d 'Verbose mode'
complete -c ldconfig -l version -d 'Print program version'

