# lgroupdel
# Autogenerated from man page /usr/share/man/man1/lgroupdel.1.gz
complete -c lgroupdel -s i -l interactive -d 'Ask all questions when connecting to the user database, even if default answe…'

