# lgroupmod
# Autogenerated from man page /usr/share/man/man1/lgroupmod.1.gz
complete -c lgroupmod -s A -l admin-add -d 'Add users in comma-separated list among group\'s administrators'
complete -c lgroupmod -s a -l admin-remove -d 'Remove users in comma-separated list from group\'s administrators'
complete -c lgroupmod -s g -l gid -d 'Change group\'s group ID to gid'
complete -c lgroupmod -s i -l interactive -d 'Ask all questions when connecting to the user database, even if default answe…'
complete -c lgroupmod -s L -l lock -d 'Lock group'
complete -c lgroupmod -s M -l member-add -d 'Add users in comma-separated list among group\'s members'
complete -c lgroupmod -s m -l member-remove -d 'Remove users in comma-separated list from group\'s members'
complete -c lgroupmod -s n -l name -d 'Rename group to name'
complete -c lgroupmod -s P -l plainpassword -d 'Set group\'s password to password'
complete -c lgroupmod -s p -l password -d 'Set group\'s password to the password represented by the hash encrypted'
complete -c lgroupmod -s U -l unlock -d 'Unlock group'

