# lgroupadd
# Autogenerated from man page /usr/share/man/man1/lgroupadd.1.gz
complete -c lgroupadd -s g -l gid -d 'Use group ID gid for the newly created group'
complete -c lgroupadd -s i -l interactive -d 'Ask all questions when connecting to the user database, even if default answe…'
complete -c lgroupadd -s r -l reserved -d 'The group is a system group'

