# lid
# Autogenerated from man page /usr/share/man/man1/lid.1.gz
complete -c lid -s g -l group -d 'List users in a group name, or in the invoking user\'s primary group if name i…'
complete -c lid -s i -l interactive -d 'Ask all questions when connecting to the user database, even if default answe…'
complete -c lid -s n -l onlynames -d 'List only group or user names'

