# lnewusers
# Autogenerated from man page /usr/share/man/man1/lnewusers.1.gz
complete -c lnewusers -s f -l file -d 'Read account data from file instead of standard input'
complete -c lnewusers -s i -l interactive -d 'Ask all questions when connecting to the user database, even if default answe…'
complete -c lnewusers -s M -l nocreatehome -d 'Don\'t create home directories'
complete -c lnewusers -s n -l nocreatemail -d 'Don\'t create mail spool files'

