# lpasswd
# Autogenerated from man page /usr/share/man/man1/lpasswd.1.gz
complete -c lpasswd -s F -l plainpassword-fd -d 'Read password from file descriptor fd, terminated by end of file, \'\\\\r\' or \'\\…'
complete -c lpasswd -s f -l password-fd -d 'Read password hash from file descriptor fd, terminated by end of file, \'\\\\r\' …'
complete -c lpasswd -s g -l group -d 'Change password of group name'
complete -c lpasswd -s i -l interactive -d 'Ask all questions when connecting to the user database, even if default answe…'
complete -c lpasswd -s P -l plainpassword -d 'Set the password to password'
complete -c lpasswd -s p -l password -d 'Set the password to the password represented by the hash encrypted'

