# lsinitrd
# Autogenerated from man page /usr/share/man/man1/lsinitrd.1.gz
complete -c lsinitrd -s h -l help -d 'print a help message and exit'
complete -c lsinitrd -s s -l size -d 'sort the contents of the initramfs by size'
complete -c lsinitrd -s f -l 'file<filename>' -d 'print the contents of <filename>'
complete -c lsinitrd -s k -l 'kver<kernel' -d 'inspect the initramfs of <kernel version>'
complete -c lsinitrd -s m -l mod -d 'list dracut modules included of the initramfs image'
complete -c lsinitrd -l unpack -d 'unpack the initramfs to the current directory, instead of displaying the cont…'
complete -c lsinitrd -l unpackearly -d 'unpack the early microcode initramfs to the current directory, instead of dis…'
complete -c lsinitrd -s v -l verbose -d 'unpack verbosely'
complete -c lsinitrd -l file
complete -c lsinitrd -l kver

