# lto-dump
# Autogenerated from man page /usr/share/man/man1/lto-dump.1.gz
complete -c lto-dump -o list -d 'X Item "-list" Dumps list of details of functions and variables'
complete -c lto-dump -o demangle -d 'X Item "-demangle" Dump the demangled output'
complete -c lto-dump -o defined-only -d 'X Item "-defined-only" Dump only the defined symbols'
complete -c lto-dump -o print-value -d 'X Item "-print-value" Dump initial values of the variables'
complete -c lto-dump -o name-sort -d 'X Item "-name-sort" Sort the symbols alphabetically'
complete -c lto-dump -o size-sort -d 'X Item "-size-sort" Sort the symbols according to size'
complete -c lto-dump -o reverse-sort -d 'X Item "-reverse-sort" Dump the symbols in reverse order'
complete -c lto-dump -o no-sort -d 'X Item "-no-sort" Dump the symbols in order of occurrence'
complete -c lto-dump -o symbol -d 'X Item "-symbol=" Dump the details of specific symbol'
complete -c lto-dump -o objects -d 'X Item "-objects" Dump the details of LTO objects'
complete -c lto-dump -o type-stats -d 'X Item "-type-stats" Dump the statistics of tree types'
complete -c lto-dump -o tree-stats -d 'X Item "-tree-stats" Dump the statistics of trees'
complete -c lto-dump -o gimple-stats -d 'X Item "-gimple-stats" Dump the statistics of gimple statements'
complete -c lto-dump -o dump-level -d 'X Item "-dump-level=" For deciding the optimization level of body'
complete -c lto-dump -o dump-body -d 'X Item "-dump-body=" Dump the specific gimple body'
complete -c lto-dump -o help

