# luserdel
# Autogenerated from man page /usr/share/man/man1/luserdel.1.gz
complete -c luserdel -s G -l dontremovegroup -d 'By default the user\'s primary group is removed if it has group name user (use…'
complete -c luserdel -s i -l interactive -d 'Ask all questions when connecting to the user database, even if default answe…'
complete -c luserdel -s r -l removehome -d 'Remove user\'s home directory and mail spool after deleting the user'

