# makedeltarpm
# Autogenerated from man page /usr/share/man/man8/makedeltarpm.8.gz
complete -c makedeltarpm -s v -d 'option to make makedeltarpm more verbose about its work (use it twice to make…'
complete -c makedeltarpm -s r -d option
complete -c makedeltarpm -s V -d 'option to specify a different version if desired.  The'
complete -c makedeltarpm -s z -d 'option can be used to specify a different compression method, the default is …'
complete -c makedeltarpm -s s -d 'option makes makedeltarpm write out the sequence id to the specified file seq…'
complete -c makedeltarpm -s p -d 'option to specify the rpm-print of oldrpm and the created patch rpm'
complete -c makedeltarpm -s u -d 'switch.  In this case only one rpm has to be specified'
complete -c makedeltarpm -s m -d 'option to enable a sliding block algorithm that needs mbytes megabytes of mem…'

