# matchpathcon
# Autogenerated from man page /usr/share/man/man8/matchpathcon.8.gz
complete -c matchpathcon -s m -d 'Force file type for the lookup'
complete -c matchpathcon -s n -d 'Do not display path'
complete -c matchpathcon -s N -d 'Do not use translations'
complete -c matchpathcon -s f -d 'Use alternate file_context file'
complete -c matchpathcon -s p -d 'Use prefix to speed up translations'
complete -c matchpathcon -s P -d 'Use alternate policy root path'
complete -c matchpathcon -s V -d 'Verify file context on disk matches defaults'

