# mkpasswd
# Autogenerated from man page /usr/share/man/man1/mkpasswd.1.gz
complete -c mkpasswd -s S -d '--salt= STRING Use the  STRING as salt'
complete -c mkpasswd -s R -d '--rounds= NUMBER Use  NUMBER rounds'
complete -c mkpasswd -s m -d '--method= TYPE Compute the password using the  TYPE method'
complete -c mkpasswd -s 5 -d 'Like R --method=md5crypt '
complete -c mkpasswd -s P -d 'R NUM ", "\\c  --password-fd= NUM Read the password from file descriptor  NUM …'
complete -c mkpasswd -l salt -d 'Use the STRING as salt'
complete -c mkpasswd -l rounds -d 'Use NUMBER rounds'
complete -c mkpasswd -l method
complete -c mkpasswd -l password-fd -d 'Read the password from file descriptor NUM instead of using getpass (3)'
complete -c mkpasswd -s s -l stdin -d Like

