# mmdblookup
# Autogenerated from man page /usr/share/man/man1/mmdblookup.1.gz
complete -c mmdblookup -s f -l file -d 'The path to the MMDB file.  Required'
complete -c mmdblookup -s i -l ip -d 'The IP address to look up.  Required'
complete -c mmdblookup -s v -l verbose -d 'Turns on verbose output'
complete -c mmdblookup -l version -d 'Print the program\\[aq]s version number and exit'
complete -c mmdblookup -s h -s '?' -l help -d 'Show usage information.  BUG REPORTS AND PULL REQUESTS'

