# modulemd-validator
# Autogenerated from man page /usr/share/man/man1/modulemd-validator.1.gz
complete -c modulemd-validator -l type -d 'Constrain a document type.  The recognized types are: . RS'
complete -c modulemd-validator -l debug -d 'Output debugging messages'
complete -c modulemd-validator -s q -l quiet -d 'Print no output'
complete -c modulemd-validator -s v -l verbose -d 'Be verbose'
complete -c modulemd-validator -s h -l help -d 'Print a usage text and then exit'
complete -c modulemd-validator -s V -l version -d 'Print a version number and then exit'

