# osinfo-db-import
# Autogenerated from man page /usr/share/man/man1/osinfo-db-import.1.gz
complete -c osinfo-db-import -l user -d 'X Item "--user" Override the default behaviour to force installation into the…'
complete -c osinfo-db-import -l local -d 'X Item "--local" Override the default behaviour to force installation into th…'
complete -c osinfo-db-import -l system -d 'X Item "--system" Override the default behaviour to force installation into t…'
complete -c osinfo-db-import -l dir -d 'X Item "--dir=PATH" Override the default behaviour to force installation into…'
complete -c osinfo-db-import -l root -d 'X Item "--root=PATH" Prefix the installation location with the root directory…'
complete -c osinfo-db-import -l latest -d 'X Item "--latest" Downloads the latest osinfo-db release from libosinfo\'s off…'
complete -c osinfo-db-import -l nightly -d 'X Item "--nightly" Downloads the nightly (unreleased) osinfo-db build from li…'
complete -c osinfo-db-import -s v -l verbose

