# osinfo-db-export
# Autogenerated from man page /usr/share/man/man1/osinfo-db-export.1.gz
complete -c osinfo-db-export -l user -d 'X Item "--user" Override the default behaviour to force archiving files from …'
complete -c osinfo-db-export -l local -d 'X Item "--local" Override the default behaviour to force archiving files from…'
complete -c osinfo-db-export -l system -d 'X Item "--system" Override the default behaviour to force archiving files fro…'
complete -c osinfo-db-export -l dir -d 'X Item "--dir=PATH" Override the default behaviour to force archiving files f…'
complete -c osinfo-db-export -l root -d 'X Item "--root=PATH" Prefix the database location with the root directory giv…'
complete -c osinfo-db-export -l version -d 'X Item "--version=VERSION" Set the version string for the files in the archiv…'
complete -c osinfo-db-export -l license -d 'X Item "--license=LICENSE-FILE" Add \\f(CW\\*(C`LICENSE-FILE\\*(C\' to the genera…'
complete -c osinfo-db-export -s v -l verbose

