# osinfo-query
# Autogenerated from man page /usr/share/man/man1/osinfo-query.1.gz
complete -c osinfo-query -s s -l sort-key -d 'X Item "-s PROPERTY, --sort-key PROPERTY" Set the data sorting key'
complete -c osinfo-query -s f -l fields

