# osinfo-install-script
# Autogenerated from man page /usr/share/man/man1/osinfo-install-script.1.gz
complete -c osinfo-install-script -l profile -d 'X Item "--profile=NAME" Choose the installation script profile'
complete -c osinfo-install-script -l installation-source -d 'X Item "--installation-source=NAME" Set the installation source to be used wi…'
complete -c osinfo-install-script -l config -d 'X Item "--config=key=value" Set the configuration parameter \\f(CW\\*(C`key\\*(C…'
complete -c osinfo-install-script -l config-file

