# osinfo-db-validate
# Autogenerated from man page /usr/share/man/man1/osinfo-db-validate.1.gz
complete -c osinfo-db-validate -l user -d 'X Item "--user" Override the default behaviour to force validating files from…'
complete -c osinfo-db-validate -l local -d 'X Item "--local" Override the default behaviour to force validating files fro…'
complete -c osinfo-db-validate -l system -d 'X Item "--system" Override the default behaviour to force validating files fr…'
complete -c osinfo-db-validate -l dir -d 'X Item "--dir=PATH" Override the default behaviour to force validating files …'
complete -c osinfo-db-validate -l root -d 'X Item "--root=PATH" Prefix the database location with the root directory giv…'
complete -c osinfo-db-validate -s v -l verbose

