# osinfo-db-path
# Autogenerated from man page /usr/share/man/man1/osinfo-db-path.1.gz
complete -c osinfo-db-path -l user -d 'X Item "--user" Override the default behaviour to force reporting of the user…'
complete -c osinfo-db-path -l local -d 'X Item "--local" Override the default behaviour to force reporting of the loc…'
complete -c osinfo-db-path -l system -d 'X Item "--system" Override the default behaviour to force reporting of the sy…'
complete -c osinfo-db-path -l dir -d 'X Item "--dir=PATH" Override the default behaviour to force reporting of the …'
complete -c osinfo-db-path -l root

