# osinfo-detect
# Autogenerated from man page /usr/share/man/man1/osinfo-detect.1.gz
complete -c osinfo-detect -l format -d 'X Item "--format=plain"'
complete -c osinfo-detect -l type -d 'X Item "--type=media|tree" '
complete -c osinfo-detect -l all

