# passwd
# Autogenerated from man page /usr/share/man/man1/passwd.1.gz
complete -c passwd -s k -l keep-tokens -d 'The option  -k is used to indicate that the update should only be for expired…'
complete -c passwd -s l -l lock -d 'This option is used to lock the password of specified account and it is avail…'
complete -c passwd -l stdin -d 'This option is used to indicate that passwd should read the new password from…'
complete -c passwd -s u -l unlock -d 'This is the reverse of the  -l " option - it will unlock the account" passwor…'
complete -c passwd -s d -l delete -d 'This is a quick way to delete a password for an account'
complete -c passwd -s e -l expire -d 'This is a quick way to expire a password for an account'
complete -c passwd -s f -l force -d 'Force the specified operation'
complete -c passwd -s n -l minimum -d 'This will set the minimum password lifetime, in days, if the user\'s account s…'
complete -c passwd -s x -l maximum -d 'This will set the maximum password lifetime, in days, if the user\'s account s…'
complete -c passwd -s w -l warning -d 'This will set the number of days in advance the user will begin receiving war…'
complete -c passwd -s i -l inactive -d 'This will set the number of days which will pass before an expired password f…'
complete -c passwd -s S -l status -d 'This will output a short information about the status of the password for a g…'
complete -c passwd -s '?' -l help -d 'Print a help message and exit'
complete -c passwd -l usage -d 'Print a short usage message and exit'

