# piconv
# Autogenerated from man page /usr/share/man/man1/piconv.1.gz
complete -c piconv -s f -l from
complete -c piconv -s t -l to
complete -c piconv -s s -l string
complete -c piconv -s l -l list
complete -c piconv -s r -l resolve
complete -c piconv -s C -l check
complete -c piconv -s c
complete -c piconv -s p -l perlqq
complete -c piconv -l htmlcref
complete -c piconv -l xmlcref
complete -c piconv -s h -l help
complete -c piconv -s D -l debug
complete -c piconv -s S -l scheme

