# pkla-check-authorization
# Autogenerated from man page /usr/share/man/man8/pkla-check-authorization.8.gz
complete -c pkla-check-authorization -s h -l help -d 'Write a summary of the available options to standard output and exit successf…'
complete -c pkla-check-authorization -s p -l paths -d 'Search for configuration files in semicolon-separated paths instead of the de…'

