# pkla-admin-identities
# Autogenerated from man page /usr/share/man/man8/pkla-admin-identities.8.gz
complete -c pkla-admin-identities -s h -l help -d 'Write a summary of the available options to standard output and exit successf…'
complete -c pkla-admin-identities -s c -l config-path -d 'Search for configuration files in config-path instead of the default /etc/pol…'

