# plymouth-set-default-theme
# Autogenerated from man page /usr/share/man/man1/plymouth-set-default-theme.1.gz
complete -c plymouth-set-default-theme -s h -l help -d 'Show summary of options'
complete -c plymouth-set-default-theme -s l -l list -d 'List available themes'
complete -c plymouth-set-default-theme -s r -l reset -d 'Reset to default theme'
complete -c plymouth-set-default-theme -s R -l rebuild-initrd -d 'Rebuild initrd (necessary after changing theme)'

