# pod2text
# Autogenerated from man page /usr/share/man/man1/pod2text.1.gz
complete -c pod2text -s a -l alt -d 'X Item "-a, --alt" [1'
complete -c pod2text -l code -d 'X Item "--code" [1'
complete -c pod2text -s c -l color -d 'X Item "-c, --color" [1'
complete -c pod2text -s e -l encoding -d 'X Item "-e encoding, --encoding=encoding" [5'
complete -c pod2text -l errors -d 'X Item "--errors=style" [2. 5. 0] Set the error handling style'
complete -c pod2text -l guesswork -d 'X Item "--guesswork=rule[,rule. ]" [5'
complete -c pod2text -s i -l indent -d 'X Item "-i indent, --indent=indent" [1'
complete -c pod2text -s h -l help -d 'X Item "-h, --help" [1. 00] Print out usage information and exit'
complete -c pod2text -s l -l loose -d 'X Item "-l, --loose" [1'
complete -c pod2text -s m -l left-margin -l margin -d 'X Item "-m width, --left-margin=width, --margin=width" [1'
complete -c pod2text -l nourls -d 'X Item "--nourls" [2. 5'
complete -c pod2text -s o -l overstrike -d 'X Item "-o, --overstrike" [1. 06] Format the output with overstrike printing'
complete -c pod2text -s q -l quotes -d 'X Item "-q quotes, --quotes=quotes" [4'
complete -c pod2text -s s -l sentence -d 'X Item "-s, --sentence" [1'
complete -c pod2text -l stderr -d 'X Item "--stderr" [2. 1'
complete -c pod2text -s t -l termcap -d 'X Item "-t, --termcap" [1'
complete -c pod2text -s u -l utf8 -d 'X Item "-u, --utf8" [2. 2. 0] Set the output encoding to UTF-8'
complete -c pod2text -s w -l width -o width

