# pod2usage
# Autogenerated from man page /usr/share/man/man1/pod2usage.1.gz
complete -c pod2usage -o help
complete -c pod2usage -o man
complete -c pod2usage -o exit
complete -c pod2usage -o output
complete -c pod2usage -o verbose
complete -c pod2usage -o pathlist
complete -c pod2usage -o formatter
complete -c pod2usage -o utf8

