# resize.f2fs
# Autogenerated from man page /usr/share/man/man8/resize.f2fs.8.gz
complete -c 'resize.f2fs' -s t -d 'Specify the size in sectors'
complete -c 'resize.f2fs' -s d -d 'Specify the level of debugging options'
complete -c 'resize.f2fs' -s o -d 'Specify the percentage of the volume that will be used as overprovision area'
complete -c 'resize.f2fs' -s i -d 'Enable extended node bitmap'
complete -c 'resize.f2fs' -s s -d 'Enable safe resize'
complete -c 'resize.f2fs' -s V -d 'Print the version number and exit'

