# restorecon_xattr
# Autogenerated from man page /usr/share/man/man8/restorecon_xattr.8.gz
complete -c restorecon_xattr -s d -d 'delete all non-matching  security. sehash directory digest entries'
complete -c restorecon_xattr -s D -d 'delete all  security. sehash directory digest entries'
complete -c restorecon_xattr -s m -d 'do not read  /proc/mounts to obtain a list of non-seclabel mounts to be exclu…'
complete -c restorecon_xattr -s n -d 'Do not append "Match" or "No Match" to displayed digests'
complete -c restorecon_xattr -s r -d 'recursively descend directories'
complete -c restorecon_xattr -s v -d 'display SHA256 digest generated by specfile set (Note that this digest is not…'
complete -c restorecon_xattr -s e -d 'directory '

