# rpm2archive
# Autogenerated from man page /usr/share/man/man8/rpm2archive.8.gz
complete -c rpm2archive -l 'nocompression\\f' -d 'Generate uncompressed tar archive and use \\[dq]'
complete -c rpm2archive -s n -l nocompression -d 'Generate uncompressed tar archive and use [dq]'
complete -c rpm2archive -s f -l format -d 'Generate archive in specified format: pax (the default format) or cpio'

