# rpmdb
# Autogenerated from man page /usr/share/man/man8/rpmdb.8.gz
complete -c rpmdb -l rebuilddb -d 'package headers'
complete -c rpmdb -l verifydb -d database
complete -c rpmdb -l exportdb -d 'suitable for transfporting to another host or database type'
complete -c rpmdb -l importdb -d 'created by --exportdb.  SEE ALSO'

