# sefcontext_compile
# Autogenerated from man page /usr/share/man/man8/sefcontext_compile.8.gz
complete -c sefcontext_compile -s o -d 'Specify an  outputfile that must be a fully qualified file name as the  '
complete -c sefcontext_compile -s p -d 'Specify a binary policyfile that will be used to validate the context entries…'

