# semodule_package
# Autogenerated from man page /usr/share/man/man8/semodule_package.8.gz
complete -c semodule_package -s o -l outfile -d 'Policy module package file generated by this tool'
complete -c semodule_package -s s -l seuser -d 'seuser file to be included in the package'
complete -c semodule_package -s u -l user_extra -d 'user_extra file to be included in the package'
complete -c semodule_package -s m -l module -d 'Policy module file to be included in the package'
complete -c semodule_package -s f -l fc -d 'File contexts file for the module (optional)'

