# semodule_expand
# Autogenerated from man page /usr/share/man/man8/semodule_expand.8.gz
complete -c semodule_expand -s V -d 'show version'
complete -c semodule_expand -s c -d 'policy version to create'

