# semodule
# Autogenerated from man page /usr/share/man/man8/semodule.8.gz
complete -c semodule -s s -l store -d 'name of the store to operate on'
complete -c semodule -s n -l noreload -s N -d 'do not reload policy after commit'
complete -c semodule -s h -l help -d 'prints help message and quit'
complete -c semodule -s P -l preserve_tunables -d 'Preserve tunables in policy'
complete -c semodule -s C -l ignore-module-cache -d 'Recompile CIL modules built from HLL files'
complete -c semodule -s p -l path -d 'Use an alternate path for the policy root'
complete -c semodule -s S -l store-path -d 'Use an alternate path for the policy store root'
complete -c semodule -s v -l verbose -d 'be verbose'
complete -c semodule -s c -l cil -d 'Extract module as a CIL file'
complete -c semodule -s H -l hll -d 'Extract module as an HLL file'

