# sss_ssh_authorizedkeys
# Autogenerated from man page /usr/share/man/man1/sss_ssh_authorizedkeys.1.gz
complete -c sss_ssh_authorizedkeys -s d -l domain -d 'Search for user public keys in SSSD domain DOMAIN'
complete -c sss_ssh_authorizedkeys -s '?' -l help -d 'Display help message and exit'

