# sss_ssh_knownhostsproxy
# Autogenerated from man page /usr/share/man/man1/sss_ssh_knownhostsproxy.1.gz
complete -c sss_ssh_knownhostsproxy -s p -l port -d 'Use port PORT to connect to the host.  By default, port 22 is used'
complete -c sss_ssh_knownhostsproxy -s d -l domain -d 'Search for host public keys in SSSD domain DOMAIN'
complete -c sss_ssh_knownhostsproxy -s k -l pubkey -d 'Print the host ssh public keys for host HOST'
complete -c sss_ssh_knownhostsproxy -s '?' -l help -d 'Display help message and exit'

