# sssd
# Autogenerated from man page /usr/share/man/man8/sssd.8.gz
complete -c sssd -s d -l debug-level -d 'SSSD supports two representations for specifying the debug level'
complete -c sssd -l debug-timestamps -d '1: Add a timestamp to the debug messages '
complete -c sssd -l debug-microseconds -d '1: Add microseconds to the timestamp in debug messages '
complete -c sssd -l logger -d 'Location where SSSD will send log messages'
complete -c sssd -s D -l daemon -d 'Become a daemon after starting up'
complete -c sssd -s i -l interactive -d 'Run in the foreground, don\\*(Aqt become a daemon'
complete -c sssd -s c -l config -d 'Specify a non-default config file.  The default is /etc/sssd/sssd. conf'
complete -c sssd -s g -l genconf -d 'Do not start the SSSD, but refresh the configuration database from the conten…'
complete -c sssd -s s -l genconf-section -d 'Similar to "--genconf", but only refresh a single section from the configurat…'
complete -c sssd -s '?' -l help -d 'Display help message and exit'
complete -c sssd -l version -d 'Print version number and exit'

