# tpm2_policycphash
# Autogenerated from man page /usr/share/man/man1/tpm2_policycphash.1.gz
complete -c tpm2_policycphash -s L -l policy -d 'File to save the compounded policy digest'
complete -c tpm2_policycphash -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policycphash -l cphash-input -d 'The file containing the command parameter hash of the command'
complete -c tpm2_policycphash -l cphash -d 'DEPRECATED, use [en]cphash-input instead'
complete -c tpm2_policycphash -s h -l help -d manpage
complete -c tpm2_policycphash -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policycphash -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policycphash -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policycphash -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policycphash -s n -d 'tpm2_startauthsession -S session'
complete -c tpm2_policycphash -o out -d 'tpm2_verifysignature -c signing_key. ctx -g sha256 -m policy. cphash [rs]'
complete -c tpm2_policycphash -s s -s t -s f -d 'Satisfy policycphash and execute nvsetbits tpm2_startauthsession -S session'

