# tpm2_getrandom
# Autogenerated from man page /usr/share/man/man1/tpm2_getrandom.1.gz
complete -c tpm2_getrandom -s o -l output -d 'Specifies the filename to output the raw bytes to'
complete -c tpm2_getrandom -l hex -d 'Convert the output data to hex format without a leading [lq]0x[rq]'
complete -c tpm2_getrandom -s f -l force
complete -c tpm2_getrandom -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_getrandom -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_getrandom -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_getrandom -s h -l help -d manpage
complete -c tpm2_getrandom -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_getrandom -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_getrandom -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_getrandom -s Z -l enable-errata -d 'errata fixups'

