# tpm2_policynamehash
# Autogenerated from man page /usr/share/man/man1/tpm2_policynamehash.1.gz
complete -c tpm2_policynamehash -s L -l policy -d 'File to save the compounded policy digest'
complete -c tpm2_policynamehash -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policynamehash -s n -l name -d 'The file containing the name hash of the referenced objects'
complete -c tpm2_policynamehash -s h -l help -d manpage
complete -c tpm2_policynamehash -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policynamehash -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policynamehash -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policynamehash -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policynamehash -s a
complete -c tpm2_policynamehash -s u
complete -c tpm2_policynamehash -o out
complete -c tpm2_policynamehash -s s -s t -s f
complete -c tpm2_policynamehash -s r

