# tpm2_rsaencrypt
# Autogenerated from man page /usr/share/man/man1/tpm2_rsaencrypt.1.gz
complete -c tpm2_rsaencrypt -s c -l key-context -d 'Context object pointing to the the public portion of RSA key to use for encry…'
complete -c tpm2_rsaencrypt -s o -l output -d 'Optional output file path to record the encrypted data to'
complete -c tpm2_rsaencrypt -s s -l scheme -d 'Optional, set the padding scheme (defaults to rsaes)'
complete -c tpm2_rsaencrypt -s l -l label -d 'Optional, set the label data.  Can either be a string or file path'
complete -c tpm2_rsaencrypt -s h -l help -d manpage
complete -c tpm2_rsaencrypt -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_rsaencrypt -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_rsaencrypt -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_rsaencrypt -s Z -l enable-errata -d 'errata fixups'

