# tpm2_certifycreation
# Autogenerated from man page /usr/share/man/man1/tpm2_certifycreation.1.gz
complete -c tpm2_certifycreation -s C -l signingkey-context -d 'Context object pointing to the key used that signs the attestation'
complete -c tpm2_certifycreation -s P -l signingkey-auth_AUTH_ -d 'Optional authorization value to use for the key specified by'
complete -c tpm2_certifycreation -s c -l certifiedkey-context -d 'Context object pointing to the key that has to be certified'
complete -c tpm2_certifycreation -s g -l hash-algorithm -d 'The hash algorithm used to digest the creation data'
complete -c tpm2_certifycreation -s s -l scheme -d 'The signing scheme used to sign the attestation data'
complete -c tpm2_certifycreation -s d -l creation-hash -d 'File containing the digest of the creation data'
complete -c tpm2_certifycreation -s t -l ticket -d 'The ticket file to validate that the creation data was produced by the TPM'
complete -c tpm2_certifycreation -s o -l signature -d 'File containing the signature of the attestation data for the certified key'
complete -c tpm2_certifycreation -s f -l format -d 'Output signature format selection'
complete -c tpm2_certifycreation -s q -l qualification -d 'Optional, the policy qualifier data that the signer can choose to include in …'
complete -c tpm2_certifycreation -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_certifycreation -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_certifycreation -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_certifycreation -s h -l help -d manpage
complete -c tpm2_certifycreation -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_certifycreation -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_certifycreation -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_certifycreation -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_certifycreation -l attestation

