# tpm2_sign
# Autogenerated from man page /usr/share/man/man1/tpm2_sign.1.gz
complete -c tpm2_sign -s c -l key-context -d 'Context object pointing to the the key used for signing'
complete -c tpm2_sign -s p -l auth_AUTH_ -d 'Optional authorization value to use the key specified by -c'
complete -c tpm2_sign -s g -l hash-algorithm -d 'The hash algorithm used to digest the message'
complete -c tpm2_sign -s s -l scheme -d 'The signing scheme used to sign the message.  Optional'
complete -c tpm2_sign -s d -l digest -d 'Indicate that FILE is a file containing the digest of the message'
complete -c tpm2_sign -s t -l ticket -d 'The ticket file, containing the validation structure, optional'
complete -c tpm2_sign -s o -l signature -d 'The signature file, records the signature structure'
complete -c tpm2_sign -s f -l format -d 'Format selection for the signature output file'
complete -c tpm2_sign -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_sign -l commit-index -d 'The commit counter value to determine the key index to use in an ECDAA signin…'
complete -c tpm2_sign -s h -l help -d manpage
complete -c tpm2_sign -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_sign -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_sign -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_sign -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_sign -o signature -d Returns

