# tpm2_encryptdecrypt
# Autogenerated from man page /usr/share/man/man1/tpm2_encryptdecrypt.1.gz
complete -c tpm2_encryptdecrypt -s c -l key-context -d 'The encryption key object'
complete -c tpm2_encryptdecrypt -s p -l auth -d 'The authorization value for the encryption key object'
complete -c tpm2_encryptdecrypt -s d -l decrypt -d 'Perform a decrypt operation'
complete -c tpm2_encryptdecrypt -s e -l pad -d 'Enable pkcs7 padding for applicable AES encryption modes cfb/cbc/ecb'
complete -c tpm2_encryptdecrypt -s o -l output -d 'The output file path for either the encrypted or decrypted data'
complete -c tpm2_encryptdecrypt -s G -l mode -d 'The key algorithm associated with this object'
complete -c tpm2_encryptdecrypt -s t -l iv -d 'Optional initialization vector to use.  Defaults to 0[cq]s'
complete -c tpm2_encryptdecrypt -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_encryptdecrypt -s h -l help -d manpage
complete -c tpm2_encryptdecrypt -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_encryptdecrypt -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_encryptdecrypt -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_encryptdecrypt -s Z -l enable-errata -d 'errata fixups'

