# tpm2_flushcontext
# Autogenerated from man page /usr/share/man/man1/tpm2_flushcontext.1.gz
complete -c tpm2_flushcontext -s t -l transient-object -d 'Remove all transient objects'
complete -c tpm2_flushcontext -s l -l loaded-session -d 'Remove all loaded sessions'
complete -c tpm2_flushcontext -s s -l saved-session -d 'Remove all saved sessions'
complete -c tpm2_flushcontext -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_flushcontext -s h -l help -d manpage
complete -c tpm2_flushcontext -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_flushcontext -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_flushcontext -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_flushcontext -s Z -l enable-errata -d 'errata fixups'

