# tpm2_import
# Autogenerated from man page /usr/share/man/man1/tpm2_import.1.gz
complete -c tpm2_import -s G -l key-algorithm
complete -c tpm2_import -s g -l hash-algorithm -d 'The hash algorithm for generating the objects name'
complete -c tpm2_import -s i -l input -d 'Specifies the filename of the key to be imported'
complete -c tpm2_import -s C -l parent-context -d 'The parent key object'
complete -c tpm2_import -s U -l parent-public -d 'Optional.  Specifies the parent key public data file input'
complete -c tpm2_import -s k -l encryption-key -d Optional
complete -c tpm2_import -s r -l private -d 'Specifies the file path required to save the encrypted private portion of the…'
complete -c tpm2_import -s u -l public -d 'Specifies the file path required to save the public portion of the object imp…'
complete -c tpm2_import -s a -l attributes -d 'The object attributes, optional'
complete -c tpm2_import -s P -l parent-auth -d 'The authorization value for using the parent key specified with'
complete -c tpm2_import -s p -l key-auth -d 'The authorization value for the imported key, optional'
complete -c tpm2_import -s L -l policy -d 'HEX_STRING: The policy file or policy hex string used for authorization to th…'
complete -c tpm2_import -s s -l seed -d 'Specifies the file containing the encrypted seed of the duplicated object'
complete -c tpm2_import -l passin -d 'An optional password for an Open SSL (OSSL) provided input file'
complete -c tpm2_import -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_import -s h -l help -d manpage
complete -c tpm2_import -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_import -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_import -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_import -s Z -l enable-errata -d 'errata fixups'

