# tpm2_getekcertificate
# Autogenerated from man page /usr/share/man/man1/tpm2_getekcertificate.1.gz
complete -c tpm2_getekcertificate -s o -l ek-certificate -d 'STDOUT: The file to save the Endorsement key certificate'
complete -c tpm2_getekcertificate -s X -l allow-unverified -d 'Specifies to attempt connecting with the TPM manufacturer provisioning server…'
complete -c tpm2_getekcertificate -s u -l ek-public -d 'Specifies the file path for the endorsement key public portion in tss format'
complete -c tpm2_getekcertificate -s x -l offline -d 'This flags the tool to operate in an offline mode'
complete -c tpm2_getekcertificate -s h -l help -d manpage
complete -c tpm2_getekcertificate -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_getekcertificate -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_getekcertificate -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_getekcertificate -s Z -l enable-errata -d 'errata fixups'

