# tpm2_policysigned
# Autogenerated from man page /usr/share/man/man1/tpm2_policysigned.1.gz
complete -c tpm2_policysigned -s L -l policy -d 'File to save the compounded policy digest'
complete -c tpm2_policysigned -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policysigned -s c -l key-context -d 'Context object for the key context used for the operation'
complete -c tpm2_policysigned -s g -l hash-algorithm -d 'The hash algorithm used to digest the message'
complete -c tpm2_policysigned -s s -l signature -d 'The input signature file of the signature to be validated'
complete -c tpm2_policysigned -s f -l format -d 'Set the input signature file to a specified format.  The default is the tpm2'
complete -c tpm2_policysigned -s t -l expiration -d 'Set the expiration time of the policy in seconds'
complete -c tpm2_policysigned -l cphash-input -d 'The command parameter hash (cpHash), enforcing the TPM command to be authoriz…'
complete -c tpm2_policysigned -l ticket -d 'The ticket file to record the authorization ticket structure'
complete -c tpm2_policysigned -l timeout -d 'The file path to record the timeout structure returned'
complete -c tpm2_policysigned -s q -l qualification -d 'Optional, the policy qualifier data that the signer can choose to include in …'
complete -c tpm2_policysigned -s x -l nonce-tpm -d 'Enable the comparison of the current session[cq]s nonceTPM to ensure the vali…'
complete -c tpm2_policysigned -s h -l help -d manpage
complete -c tpm2_policysigned -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policysigned -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policysigned -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policysigned -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policysigned -s i -d 'Satisfy the policy and unseal secret tpm2_startauthsession -S session'

