# tpm2_startauthsession
# Autogenerated from man page /usr/share/man/man1/tpm2_startauthsession.1.gz
complete -c tpm2_startauthsession -s a -d 'Saves the policy session data to a file'
complete -c tpm2_startauthsession -l policy-session -d 'Start a policy session of type TPM_SE_POLICY'
complete -c tpm2_startauthsession -l audit-session -d 'Start an HMAC session to be used as an audit session'
complete -c tpm2_startauthsession -l hmac-session -d 'Start an HMAC session of type TPM_SE_HMAC'
complete -c tpm2_startauthsession -s g -l hash-algorithm -d 'The hash algorithm used in computation of the policy digest'
complete -c tpm2_startauthsession -s G -l key-algorithm -d 'The symmetric algorithm used in parameter encryption/decryption'
complete -c tpm2_startauthsession -s c -l key-context -d 'Set the tpmkey and bind objects to be the same'
complete -c tpm2_startauthsession -s S -l session -d 'The name of the policy session file, required'
complete -c tpm2_startauthsession -l bind-context -d 'Set the bind object.  Session parameter encryption is off'
complete -c tpm2_startauthsession -l bind-auth -d 'Set the authorization value for the bind object'
complete -c tpm2_startauthsession -l tpmkey-context -d 'Set the tpmkey object.  Session parameter encryption is off'
complete -c tpm2_startauthsession -s n -l name -d 'A name file as output from a tool like tpm2_readpublic(1) -n option'
complete -c tpm2_startauthsession -s h -l help -d manpage
complete -c tpm2_startauthsession -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_startauthsession -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_startauthsession -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_startauthsession -s Z -l enable-errata -d 'errata fixups'

