# tpm2_setclock
# Autogenerated from man page /usr/share/man/man1/tpm2_setclock.1.gz
complete -c tpm2_setclock -s c -l hierarchy -d 'The hierarchy to use for authorization, either platform or owner'
complete -c tpm2_setclock -s p -l auth -d 'Specifies the authorization value for the hierarchy specified by option'
complete -c tpm2_setclock -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_setclock -s h -l help -d manpage
complete -c tpm2_setclock -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_setclock -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_setclock -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_setclock -s Z -l enable-errata -d 'errata fixups'

