# tpm2_policyauthorizenv
# Autogenerated from man page /usr/share/man/man1/tpm2_policyauthorizenv.1.gz
complete -c tpm2_policyauthorizenv -s C -l hierarchy
complete -c tpm2_policyauthorizenv -s P -l auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_policyauthorizenv -s L -l policy -d 'File to save the policy digest'
complete -c tpm2_policyauthorizenv -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policyauthorizenv -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_policyauthorizenv -s h -l help -d manpage
complete -c tpm2_policyauthorizenv -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policyauthorizenv -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policyauthorizenv -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policyauthorizenv -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policyauthorizenv -s a -o i-

