# tpm2_policycountertimer
# Autogenerated from man page /usr/share/man/man1/tpm2_policycountertimer.1.gz
complete -c tpm2_policycountertimer -s L -l policy -d 'File to save the policy digest'
complete -c tpm2_policycountertimer -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession …'
complete -c tpm2_policycountertimer -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_policycountertimer -s h -l help -d manpage
complete -c tpm2_policycountertimer -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policycountertimer -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policycountertimer -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policycountertimer -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policycountertimer -s a -s c -d 'Unsealing should work in the first minute after TPM restart tpm2_startauthses…'

