# tpm2_startup
# Autogenerated from man page /usr/share/man/man1/tpm2_startup.1.gz
complete -c tpm2_startup -s c -l clear -d 'Startup type sent will be TPM_SU_CLEAR instead of TPM2_SU_STATE'
complete -c tpm2_startup -s h -l help -d manpage
complete -c tpm2_startup -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_startup -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_startup -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_startup -s Z -l enable-errata -d 'errata fixups'

