# tpm2_makecredential
# Autogenerated from man page /usr/share/man/man1/tpm2_makecredential.1.gz
complete -c tpm2_makecredential -s e -l encryption-key -d 'DEPRECATED, use -u or [en]public instead'
complete -c tpm2_makecredential -s u -l public -d 'A TPM public key which was used to wrap the seed'
complete -c tpm2_makecredential -s G -l key-algorithm -d 'The key algorithm associated with TPM public key.  Specify either RSA/ ECC'
complete -c tpm2_makecredential -s s -l secret -d 'The secret which will be protected by the key derived from the random seed'
complete -c tpm2_makecredential -s n -l name -d 'The name of the key for which certificate is to be created'
complete -c tpm2_makecredential -s o -l credential-blob -d 'The output file path, recording the encrypted-user-chosen-data and the wrappe…'
complete -c tpm2_makecredential -s h -l help -d manpage
complete -c tpm2_makecredential -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_makecredential -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_makecredential -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_makecredential -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_makecredential -s p

