# tpm2_changeeps
# Autogenerated from man page /usr/share/man/man1/tpm2_changeeps.1.gz
complete -c tpm2_changeeps -s p -l auth -d 'Specifies the AUTH for the platform.  hierarchy'
complete -c tpm2_changeeps -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_changeeps -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_changeeps -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_changeeps -s v -d 'The [lq]default-tcti[rq] key-value pair will indicate which of the aforementi…'

