# tpm2_rc_decode
# Autogenerated from man page /usr/share/man/man1/tpm2_rc_decode.1.gz
complete -c tpm2_rc_decode -s h -l help -d manpage
complete -c tpm2_rc_decode -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_rc_decode -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_rc_decode -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_rc_decode -s Z -l enable-errata -d 'errata fixups'

