# tpm2_policypcr
# Autogenerated from man page /usr/share/man/man1/tpm2_policypcr.1.gz
complete -c tpm2_policypcr -s L -l policy -d 'File to save the policy digest'
complete -c tpm2_policypcr -s f -l pcr -d 'Optional Path or Name of the file containing expected PCR values for the spec…'
complete -c tpm2_policypcr -s l -l pcr-list -d 'The list of PCR banks and selected PCRs[cq] ids for each bank'
complete -c tpm2_policypcr -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policypcr -s h -l help -d manpage
complete -c tpm2_policypcr -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policypcr -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policypcr -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policypcr -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policypcr -o i-
complete -c tpm2_policypcr -s c -d 'Step 3: Satisfy the policy tpm2_startauthsession --policy-session -S session'

