# tpm2_setprimarypolicy
# Autogenerated from man page /usr/share/man/man1/tpm2_setprimarypolicy.1.gz
complete -c tpm2_setprimarypolicy -s C -l hierarchy -d 'Specifies the hierarchy whose authorization policy is to be setup'
complete -c tpm2_setprimarypolicy -s P -l auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_setprimarypolicy -s L -l policy -d 'The file path of the authorization policy data'
complete -c tpm2_setprimarypolicy -s g -l hash-algorithm -d 'The hash algorithm used in computation of the policy digest'
complete -c tpm2_setprimarypolicy -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_setprimarypolicy -s h -l help -d manpage
complete -c tpm2_setprimarypolicy -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_setprimarypolicy -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_setprimarypolicy -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_setprimarypolicy -s Z -l enable-errata -d 'errata fixups'

