# tpm2_sessionconfig
# Autogenerated from man page /usr/share/man/man1/tpm2_sessionconfig.1.gz
complete -c tpm2_sessionconfig -l enable-continuesession -d 'Enable continueSession in the session-attributes'
complete -c tpm2_sessionconfig -l disable-continuesession -d 'Disable continuesession in the session-attributes'
complete -c tpm2_sessionconfig -l enable-auditexclusive -d 'Enable auditexclusive in the session-attributes'
complete -c tpm2_sessionconfig -l disable-auditexclusive -d 'Disable auditexclusive in the session-attributes'
complete -c tpm2_sessionconfig -l enable-auditreset -d 'Enable auditreset in the session-attributes'
complete -c tpm2_sessionconfig -l disable-auditreset -d 'Disable auditreset in the session-attributes'
complete -c tpm2_sessionconfig -l enable-decrypt -d 'Enable decrypt in the session-attributes'
complete -c tpm2_sessionconfig -l disable-decrypt -d 'Disable decrypt in the session-attributes'
complete -c tpm2_sessionconfig -l enable-encrypt -d 'Enable encrypt in the session-attributes'
complete -c tpm2_sessionconfig -l disable-encrypt -d 'Disable encrypt in the session-attributes'
complete -c tpm2_sessionconfig -l enable-audit -d 'Enable audit in the session-attributes'
complete -c tpm2_sessionconfig -l disable-audit -d 'Disable audit in the session-attributes'
complete -c tpm2_sessionconfig -s h -l help -d manpage
complete -c tpm2_sessionconfig -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_sessionconfig -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_sessionconfig -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_sessionconfig -s Z -l enable-errata -d 'errata fixups'

