# tpm2_nvwrite
# Autogenerated from man page /usr/share/man/man1/tpm2_nvwrite.1.gz
complete -c tpm2_nvwrite -s i -l input -d 'This is a mandatory input to specify the input file with data to write to NV'
complete -c tpm2_nvwrite -s C -l hierarchy
complete -c tpm2_nvwrite -s P -l auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_nvwrite -l offset -d 'The offset within the NV index to start writing at'
complete -c tpm2_nvwrite -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_nvwrite -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_nvwrite -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_nvwrite -s n -l name -d 'The name of the NV index that must be provided when only calculating the cpHa…'
complete -c tpm2_nvwrite -s h -l help -d manpage
complete -c tpm2_nvwrite -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_nvwrite -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_nvwrite -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_nvwrite -s Z -l enable-errata -d 'errata fixups'

