# tpm2_pcrevent
# Autogenerated from man page /usr/share/man/man1/tpm2_pcrevent.1.gz
complete -c tpm2_pcrevent -s P -l auth -d 'Specifies the authorization value for PCR'
complete -c tpm2_pcrevent -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_pcrevent -s h -l help -d manpage
complete -c tpm2_pcrevent -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_pcrevent -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_pcrevent -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_pcrevent -s Z -l enable-errata -d 'errata fixups'

