# tpm2_geteccparameters
# Autogenerated from man page /usr/share/man/man1/tpm2_geteccparameters.1.gz
complete -c tpm2_geteccparameters -s o -l output -d 'Specify the file path to save the ECC parameters'
complete -c tpm2_geteccparameters -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_geteccparameters -s h -l help -d manpage
complete -c tpm2_geteccparameters -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_geteccparameters -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_geteccparameters -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_geteccparameters -s Z -l enable-errata -d 'errata fixups'

