# tpm2_pcrallocate
# Autogenerated from man page /usr/share/man/man1/tpm2_pcrallocate.1.gz
complete -c tpm2_pcrallocate -s P -l auth -d 'Optional authorization value'
complete -c tpm2_pcrallocate -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_pcrallocate -s h -l help -d manpage
complete -c tpm2_pcrallocate -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_pcrallocate -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_pcrallocate -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_pcrallocate -s Z -l enable-errata -d 'errata fixups'

