# tpm2_nvread
# Autogenerated from man page /usr/share/man/man1/tpm2_nvread.1.gz
complete -c tpm2_nvread -s C -l hierarchy
complete -c tpm2_nvread -s o -l output -d 'File to write data'
complete -c tpm2_nvread -s P -l auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_nvread -s s -l size -d 'Specifies the size of data to be read in bytes, starting from 0 if offset is …'
complete -c tpm2_nvread -l offset -d 'The offset within the NV index to start reading from'
complete -c tpm2_nvread -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_nvread -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_nvread -s n -l name -d 'The name of the NV index that must be provided when only calculating the cpHa…'
complete -c tpm2_nvread -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_nvread -l print-yaml -d 'Output the content of the NV index in a human readable format, useful for dis…'
complete -c tpm2_nvread -s h -l help -d manpage
complete -c tpm2_nvread -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_nvread -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_nvread -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_nvread -s Z -l enable-errata -d 'errata fixups'

