# tpm2_nvundefine
# Autogenerated from man page /usr/share/man/man1/tpm2_nvundefine.1.gz
complete -c tpm2_nvundefine -s C -l hierarchy
complete -c tpm2_nvundefine -s P -l auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_nvundefine -s S -l session
complete -c tpm2_nvundefine -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_nvundefine -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_nvundefine -l with-policydelete -d 'This must be specified when calculating cpHash with'
complete -c tpm2_nvundefine -l tcti -d 'This is a requirement because there is no way to know if the attribute TPMA_N…'
complete -c tpm2_nvundefine -s n -l name -d 'The name of the NV index that must be provided when only calculating the cpHa…'
complete -c tpm2_nvundefine -s h -l help -d manpage
complete -c tpm2_nvundefine -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_nvundefine -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_nvundefine -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_nvundefine -s Z -l enable-errata -d 'errata fixups'

