# tpm2_hmac
# Autogenerated from man page /usr/share/man/man1/tpm2_hmac.1.gz
complete -c tpm2_hmac -s c -l key-context -d 'The context object of the symmetric signing key providing the HMAC key'
complete -c tpm2_hmac -s p -l auth -d 'Optional authorization value to use the key specified by -c'
complete -c tpm2_hmac -s g -l hash-algorithm -d 'The hash algorithm to use'
complete -c tpm2_hmac -l hex -d 'Convert the output hmac to hex format without a leading [lq]0x[rq]'
complete -c tpm2_hmac -s o -l output -d 'Optional file record of the HMAC result.  Defaults to STDOUT'
complete -c tpm2_hmac -s t -l ticket -d 'Optional file record of the ticket result'
complete -c tpm2_hmac -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_hmac -s h -l help -d manpage
complete -c tpm2_hmac -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_hmac -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_hmac -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_hmac -s Z -l enable-errata -d 'errata fixups'

