# tpm2_eventlog
# Autogenerated from man page /usr/share/man/man1/tpm2_eventlog.1.gz
complete -c tpm2_eventlog -l eventlog-version -d 'Specifies the yaml version of parsed event log'
complete -c tpm2_eventlog -s h -l help -d manpage
complete -c tpm2_eventlog -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_eventlog -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_eventlog -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_eventlog -s Z -l enable-errata -d 'errata fixups'

