# tpm2_policyticket
# Autogenerated from man page /usr/share/man/man1/tpm2_policyticket.1.gz
complete -c tpm2_policyticket -s L -l policy -d 'File to save the compounded policy digest'
complete -c tpm2_policyticket -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policyticket -s n -l name -d 'Name of the object that validated the authorization'
complete -c tpm2_policyticket -l ticket -d 'The ticket file to record the authorization ticket structure'
complete -c tpm2_policyticket -l timeout -d 'The file path to record the timeout structure returned'
complete -c tpm2_policyticket -s q -l qualification -d 'Optional, the policy qualifier data that the signer can choose to include in …'
complete -c tpm2_policyticket -s h -l help -d manpage
complete -c tpm2_policyticket -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policyticket -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policyticket -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policyticket -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policyticket -s c
complete -c tpm2_policyticket -s C -s i -d 'Create ticket-able policy tpm2_startauthsession -S session'
complete -c tpm2_policyticket -s x
complete -c tpm2_policyticket -s t

