# tpm2_pcrread
# Autogenerated from man page /usr/share/man/man1/tpm2_pcrread.1.gz
complete -c tpm2_pcrread -s o -l output -d 'The output file to write the PCR values in binary format, optional'
complete -c tpm2_pcrread -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_pcrread -s F -l pcrs_format -d 'Format selection for the binary blob in the PCR output file'
complete -c tpm2_pcrread -s h -l help -d manpage
complete -c tpm2_pcrread -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_pcrread -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_pcrread -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_pcrread -s Z -l enable-errata -d 'errata fixups'

