# tpm2_clearcontrol
# Autogenerated from man page /usr/share/man/man1/tpm2_clearcontrol.1.gz
complete -c tpm2_clearcontrol -s C -l hierarchy -d 'Specifies what auth handle, either platform hierarchy or lockout the tool sho…'
complete -c tpm2_clearcontrol -s P -l auth -d 'The authorization value of the hierarchy specified with -C'
complete -c tpm2_clearcontrol -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_clearcontrol -s h -l help -d manpage
complete -c tpm2_clearcontrol -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_clearcontrol -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_clearcontrol -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_clearcontrol -s Z -l enable-errata -d 'errata fixups'

