# tpm2_nvreadpublic
# Autogenerated from man page /usr/share/man/man1/tpm2_nvreadpublic.1.gz
complete -c tpm2_nvreadpublic -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_nvreadpublic -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_nvreadpublic -s S -l session -d 'Specify an auxiliary session for auditing and or encryption/decryption of the…'
complete -c tpm2_nvreadpublic -s n -l name -d 'The name of the NV index that must be provided when only calculating the cpHa…'
complete -c tpm2_nvreadpublic -s h -l help -d manpage
complete -c tpm2_nvreadpublic -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_nvreadpublic -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_nvreadpublic -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_nvreadpublic -s Z -l enable-errata -d 'errata fixups'

