# tpm2_policynv
# Autogenerated from man page /usr/share/man/man1/tpm2_policynv.1.gz
complete -c tpm2_policynv -s C -l hierarchy
complete -c tpm2_policynv -s P -l auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_policynv -s L -l policy -d 'File to save the policy digest'
complete -c tpm2_policynv -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession …'
complete -c tpm2_policynv -l offset -d 'The offset within the NV index to start comparing at'
complete -c tpm2_policynv -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_policynv -s i -l input -d 'Specifies the input file with data to compare to NV Index contents'
complete -c tpm2_policynv -s h -l help -d manpage
complete -c tpm2_policynv -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policynv -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policynv -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policynv -s Z -l enable-errata -d 'errata fixups'

