# tpm2_rsadecrypt
# Autogenerated from man page /usr/share/man/man1/tpm2_rsadecrypt.1.gz
complete -c tpm2_rsadecrypt -s c -l key-context -d 'Context object pointing to the the public portion of RSA key to use for decry…'
complete -c tpm2_rsadecrypt -s p -l auth -d 'Optional authorization value to use the key specified by -c'
complete -c tpm2_rsadecrypt -s o -l output -d 'Optional output file path to record the decrypted data to'
complete -c tpm2_rsadecrypt -s s -l scheme -d 'Optional, set the padding scheme (defaults to rsaes)'
complete -c tpm2_rsadecrypt -s l -l label -d 'Optional, set the label data'
complete -c tpm2_rsadecrypt -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_rsadecrypt -s h -l help -d manpage
complete -c tpm2_rsadecrypt -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_rsadecrypt -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_rsadecrypt -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_rsadecrypt -s Z -l enable-errata -d 'errata fixups'

