# tpm2_selftest
# Autogenerated from man page /usr/share/man/man1/tpm2_selftest.1.gz
complete -c tpm2_selftest -s f -l fulltest -d 'References COMMON OPTIONS'
complete -c tpm2_selftest -s h -l help -d manpage
complete -c tpm2_selftest -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_selftest -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_selftest -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_selftest -s Z -l enable-errata -d 'errata fixups'

