# tpm2_policyor
# Autogenerated from man page /usr/share/man/man1/tpm2_policyor.1.gz
complete -c tpm2_policyor -s L -l policy -d 'File to save the compounded policy digest'
complete -c tpm2_policyor -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policyor -s l -l policy-list -d 'This option is DEPRECATED yet is retained for backwards compatibility'
complete -c tpm2_policyor -s h -l help -d manpage
complete -c tpm2_policyor -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policyor -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policyor -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policyor -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policyor -o i- -d 'Satisfy auth policy using password and unseal the secret tpm2_startauthsessio…'

