# tpm2_policytemplate
# Autogenerated from man page /usr/share/man/man1/tpm2_policytemplate.1.gz
complete -c tpm2_policytemplate -s L -l policy -d 'File to save the compounded policy digest'
complete -c tpm2_policytemplate -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policytemplate -s h -l help -d manpage
complete -c tpm2_policytemplate -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policytemplate -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policytemplate -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policytemplate -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policytemplate -l template-hash -d 'tpm2_flushcontext session. ctx'

