# tpm2_encodeobject
# Autogenerated from man page /usr/share/man/man1/tpm2_encodeobject.1.gz
complete -c tpm2_encodeobject -s C -l parent-context -d 'The parent object'
complete -c tpm2_encodeobject -s P -l auth -d 'The authorization value of the parent object specified by -C'
complete -c tpm2_encodeobject -s u -l public -d 'A file containing the public portion of the object'
complete -c tpm2_encodeobject -s r -l private -d 'A file containing the sensitive portion of the object'
complete -c tpm2_encodeobject -s p -l key-auth -d 'Indicates if an authorization value is needed for the object specified by -r …'
complete -c tpm2_encodeobject -s o -l output -d 'The output file path, recording the public portion of the object'
complete -c tpm2_encodeobject -s h -l help -d manpage
complete -c tpm2_encodeobject -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_encodeobject -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_encodeobject -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_encodeobject -s Z -l enable-errata -d 'errata fixups'

