# tpm2_evictcontrol
# Autogenerated from man page /usr/share/man/man1/tpm2_evictcontrol.1.gz
complete -c tpm2_evictcontrol -s C -l hierarchy
complete -c tpm2_evictcontrol -s c -l object-context -d 'A context object specifier of a transient or persistent object'
complete -c tpm2_evictcontrol -s P -l auth -d 'The authorization value for the hierarchy specified with -C'
complete -c tpm2_evictcontrol -s o -l output -d 'Optionally output a serialized object representing the persistent handle'
complete -c tpm2_evictcontrol -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_evictcontrol -s h -l help -d manpage
complete -c tpm2_evictcontrol -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_evictcontrol -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_evictcontrol -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_evictcontrol -s Z -l enable-errata -d 'errata fixups'

