# tpm2_ecephemeral
# Autogenerated from man page /usr/share/man/man1/tpm2_ecephemeral.1.gz
complete -c tpm2_ecephemeral -s u -l public -d 'Specify the file path to save the ephemeral public point Q [u2254] [r]G'
complete -c tpm2_ecephemeral -s t -l counter -d 'Specify file path to save the least-significant 16 bits of commit count'
complete -c tpm2_ecephemeral -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_ecephemeral -s h -l help -d manpage
complete -c tpm2_ecephemeral -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_ecephemeral -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_ecephemeral -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_ecephemeral -s Z -l enable-errata -d 'errata fixups'

