# tpm2_zgen2phase
# Autogenerated from man page /usr/share/man/man1/tpm2_zgen2phase.1.gz
complete -c tpm2_zgen2phase -s c -l key-context -d 'Context object pointing to ECC key.  Either a file or a handle number'
complete -c tpm2_zgen2phase -s p -l key-auth -d 'The authorization value for the ECC key object'
complete -c tpm2_zgen2phase -s s -l scheme -d 'The key exchange scheme.  Optional.  Valid options are ecdh or sm2'
complete -c tpm2_zgen2phase -s t -l counter -d 'The commit count to determine the key index to use'
complete -c tpm2_zgen2phase -l static-public -d 'The static public key input of the other party'
complete -c tpm2_zgen2phase -l ephemeral-public -d 'The ephemeral public key input of the other party'
complete -c tpm2_zgen2phase -l output-Z1 -d 'Specify file path to save the calculated ecdh secret Z1 point'
complete -c tpm2_zgen2phase -l output-Z2 -d 'Specify file path to save the calculated ecdh secret Z2 point'
complete -c tpm2_zgen2phase -s h -l help -d manpage
complete -c tpm2_zgen2phase -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_zgen2phase -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_zgen2phase -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_zgen2phase -s Z -l enable-errata -d 'errata fixups'

