# tpm2_getcap
# Autogenerated from man page /usr/share/man/man1/tpm2_getcap.1.gz
complete -c tpm2_getcap -s l -l list -d 'List known supported capability names'
complete -c tpm2_getcap -l ignore-moredata
complete -c tpm2_getcap -s h -l help -d manpage
complete -c tpm2_getcap -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_getcap -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_getcap -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_getcap -s Z -l enable-errata -d 'errata fixups'

