# tpm2_policyrestart
# Autogenerated from man page /usr/share/man/man1/tpm2_policyrestart.1.gz
complete -c tpm2_policyrestart -s S -l session -d 'Optional, A session file from tpm2_startauthsession(1)[cq]s'
complete -c tpm2_policyrestart -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_policyrestart -s h -l help -d manpage
complete -c tpm2_policyrestart -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policyrestart -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policyrestart -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policyrestart -s Z -l enable-errata -d 'errata fixups'

