# tpm2_ecdhkeygen
# Autogenerated from man page /usr/share/man/man1/tpm2_ecdhkeygen.1.gz
complete -c tpm2_ecdhkeygen -s c -l context -d 'Context object pointing to ECC public key.  Either a file or a handle number'
complete -c tpm2_ecdhkeygen -s u -l public -d 'Output ECC point Q'
complete -c tpm2_ecdhkeygen -s o -l output -d 'Specify file path to save the calculated ecdh secret or Z point'
complete -c tpm2_ecdhkeygen -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_ecdhkeygen -s h -l help -d manpage
complete -c tpm2_ecdhkeygen -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_ecdhkeygen -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_ecdhkeygen -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_ecdhkeygen -s Z -l enable-errata -d 'errata fixups'

