# tpm2_nvcertify
# Autogenerated from man page /usr/share/man/man1/tpm2_nvcertify.1.gz
complete -c tpm2_nvcertify -s C -l signingkey-context -d 'The key object that signs the attestation structure'
complete -c tpm2_nvcertify -s P -l signingkey-auth -d 'The authorization value provided for the object specified with -C'
complete -c tpm2_nvcertify -s c -l nvauthobj-context -d 'The object that is the authorization handle for the NV object'
complete -c tpm2_nvcertify -s p -l nvauthobj-auth -d 'The authorization value provided for the object specified with -c'
complete -c tpm2_nvcertify -s g -l hash-algorithm -d 'The hash algorithm to use in signature generation'
complete -c tpm2_nvcertify -s s -l scheme -d 'The signing scheme used to sign the attestation data'
complete -c tpm2_nvcertify -s f -l format -d 'Format selection for the signature output file'
complete -c tpm2_nvcertify -s o -l signature -d 'Output file name for the signature data'
complete -c tpm2_nvcertify -s q -l qualification -d 'Optional, the policy qualifier data that the signer can choose to include in …'
complete -c tpm2_nvcertify -l size -d 'Specifies the size of data to be read in bytes, starting from 0 if offset is …'
complete -c tpm2_nvcertify -l offset -d 'The offset within the NV index to start reading from'
complete -c tpm2_nvcertify -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_nvcertify -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_nvcertify -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_nvcertify -s n -l name -d 'The name of the NV index that must be provided when only calculating the cpHa…'
complete -c tpm2_nvcertify -o signer-name -d 'The name of the signing key that must be provided when only calculating the c…'
complete -c tpm2_nvcertify -s h -l help -d manpage
complete -c tpm2_nvcertify -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_nvcertify -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_nvcertify -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_nvcertify -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_nvcertify -l attestation -d Returns

