# tpm2_policyduplicationselect
# Autogenerated from man page /usr/share/man/man1/tpm2_policyduplicationselect.1.gz
complete -c tpm2_policyduplicationselect -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policyduplicationselect -s n -l object-name -d 'Input name file of the object to be duplicated'
complete -c tpm2_policyduplicationselect -s N -l parent-name -d 'Input name file of the new parent'
complete -c tpm2_policyduplicationselect -s L -l policy -d 'File to save the policy digest'
complete -c tpm2_policyduplicationselect -l include-object -d 'If exists, the object name will be included in the value in policy digest'
complete -c tpm2_policyduplicationselect -s h -l help -d manpage
complete -c tpm2_policyduplicationselect -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policyduplicationselect -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policyduplicationselect -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policyduplicationselect -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policyduplicationselect -s a -s c -d 'tpm2_readpublic -c dupkey. ctx -n dupkey'
complete -c tpm2_policyduplicationselect -s r -s s -d 'tpm2_flushcontext  session. ctx rm session'

