# tpm2_policyauthorize
# Autogenerated from man page /usr/share/man/man1/tpm2_policyauthorize.1.gz
complete -c tpm2_policyauthorize -s L -l policy -d 'File to save the policy digest'
complete -c tpm2_policyauthorize -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policyauthorize -s i -l input -d 'The policy digest that has to be authorized'
complete -c tpm2_policyauthorize -s q -l qualification -d 'The policy qualifier data signed in conjunction with the input policy digest'
complete -c tpm2_policyauthorize -s n -l name -d 'File containing the name of the verifying public key'
complete -c tpm2_policyauthorize -s t -l ticket -d 'The ticket file to record the validation structure'
complete -c tpm2_policyauthorize -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_policyauthorize -s h -l help -d manpage
complete -c tpm2_policyauthorize -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policyauthorize -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policyauthorize -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policyauthorize -s Z -l enable-errata -d 'errata fixups'

