# tpm2_changepps
# Autogenerated from man page /usr/share/man/man1/tpm2_changepps.1.gz
complete -c tpm2_changepps -s p -l auth -d 'platform.  hierarchy.  [bu] 2'
complete -c tpm2_changepps -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_changepps -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_changepps -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_changepps -s v -d 'The [lq]default-tcti[rq] key-value pair will indicate which of the aforementi…'

