# tpm2_unseal
# Autogenerated from man page /usr/share/man/man1/tpm2_unseal.1.gz
complete -c tpm2_unseal -s c -l object-context -d 'Object context for the loaded object'
complete -c tpm2_unseal -s p -l auth -d 'Optional auth value to use for the key specified by -c'
complete -c tpm2_unseal -s o -l output -d 'Output file name containing the unsealed data'
complete -c tpm2_unseal -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_unseal -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_unseal -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_unseal -s h -l help -d manpage
complete -c tpm2_unseal -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_unseal -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_unseal -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_unseal -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_unseal -s u -s r

