# tpm2_commit
# Autogenerated from man page /usr/share/man/man1/tpm2_commit.1.gz
complete -c tpm2_commit -l basepoint-y -d 'Specify the y coordinate of the basepoint'
complete -c tpm2_commit -l eccpoint-P -d 'Specify a point on the curve used by sign handle'
complete -c tpm2_commit -l eccpoint-K -d 'Output ECC point K [u2254] [ds](x2, y2)'
complete -c tpm2_commit -l eccpoint-L -d 'Output ECC point L [u2254] [r](x2, y2)'
complete -c tpm2_commit -s u -l public -d 'Output ECC point E [u2254] [r]P1'
complete -c tpm2_commit -s t -l counter -d 'Specify file path to save the least-significant 16 bits of commit count'
complete -c tpm2_commit -s p -l auth -d 'The authorization value for the created object'
complete -c tpm2_commit -s c -l context -d 'Context object pointing to the the key used for signing'
complete -c tpm2_commit -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_commit -s h -l help -d manpage
complete -c tpm2_commit -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_commit -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_commit -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_commit -s Z -l enable-errata -d 'errata fixups'

