# tpm2_load
# Autogenerated from man page /usr/share/man/man1/tpm2_load.1.gz
complete -c tpm2_load -s C -l parent-context -d 'The parent object'
complete -c tpm2_load -s P -l auth -d 'The authorization value of the parent object specified by -C'
complete -c tpm2_load -s u -l public -d 'A file containing the public portion of the object'
complete -c tpm2_load -s r -l private -d 'A file containing the sensitive portion of the object'
complete -c tpm2_load -s n -l name -d 'An optional file to save the name structure of the object'
complete -c tpm2_load -s c -l key-context -d 'The file name of the saved object context, required'
complete -c tpm2_load -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_load -s h -l help -d manpage
complete -c tpm2_load -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_load -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_load -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_load -s Z -l enable-errata -d 'errata fixups'

