# tpm2_pcrreset
# Autogenerated from man page /usr/share/man/man1/tpm2_pcrreset.1.gz
complete -c tpm2_pcrreset -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_pcrreset -s h -l help -d manpage
complete -c tpm2_pcrreset -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_pcrreset -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_pcrreset -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_pcrreset -s Z -l enable-errata -d 'errata fixups'

