# tpm2_policylocality
# Autogenerated from man page /usr/share/man/man1/tpm2_policylocality.1.gz
complete -c tpm2_policylocality -s S -l session -d 'A session file from tpm2_startauthsession(1)[cq]s'
complete -c tpm2_policylocality -s L -l policy -d 'File to save the policy digest'
complete -c tpm2_policylocality -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_policylocality -s h -l help -d manpage
complete -c tpm2_policylocality -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policylocality -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policylocality -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policylocality -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_policylocality -o i- -d 'Try unseal operation tpm2_load -C prim. ctx -u sealkey. pub -r sealkey'
complete -c tpm2_policylocality -s c

