# tpm2_readpublic
# Autogenerated from man page /usr/share/man/man1/tpm2_readpublic.1.gz
complete -c tpm2_readpublic -s c -l object-context -d 'Context object for the object to read'
complete -c tpm2_readpublic -s n -l name -d 'An optional file to save the name structure of the object'
complete -c tpm2_readpublic -s f -l format -d 'Format selection for the public key output file'
complete -c tpm2_readpublic -s o -l output -d 'The output file path, recording the public portion of the object'
complete -c tpm2_readpublic -s t -l serialized-handle -d 'If the object to be read is a persistent object specified by a raw handle, op…'
complete -c tpm2_readpublic -s q -l qualified-name -d 'Saves the qualified name of the object to FILE'
complete -c tpm2_readpublic -s h -l help -d manpage
complete -c tpm2_readpublic -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_readpublic -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_readpublic -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_readpublic -s Z -l enable-errata -d 'errata fixups'

