# tpm2_send
# Autogenerated from man page /usr/share/man/man1/tpm2_send.1.gz
complete -c tpm2_send -s o -l output -d 'Output file to send response buffer to.  Defaults to STDOUT'
complete -c tpm2_send -s h -l help -d manpage
complete -c tpm2_send -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_send -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_send -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_send -s Z -l enable-errata -d 'errata fixups'

