# tpm2_verifysignature
# Autogenerated from man page /usr/share/man/man1/tpm2_verifysignature.1.gz
complete -c tpm2_verifysignature -s c -l key-context -d 'Context object for the key context used for the operation'
complete -c tpm2_verifysignature -s g -l hash-algorithm -d 'The hash algorithm used to digest the message'
complete -c tpm2_verifysignature -s m -l message -d 'The message file, containing the content to be digested'
complete -c tpm2_verifysignature -s d -l digest -d 'The input hash file, containing the hash of the message'
complete -c tpm2_verifysignature -s s -l signature -d 'The input signature file of the signature to be validated'
complete -c tpm2_verifysignature -s f -l scheme -d 'The signing scheme that was used to sign the message'
complete -c tpm2_verifysignature -l format -d 'Deprecated.  Same as --scheme'
complete -c tpm2_verifysignature -s t -l ticket -d 'The ticket file to record the validation structure'
complete -c tpm2_verifysignature -s h -l help -d manpage
complete -c tpm2_verifysignature -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_verifysignature -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_verifysignature -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_verifysignature -s Z -l enable-errata -d 'errata fixups'
complete -c tpm2_verifysignature -o signature

