# tpm2_policynvwritten
# Autogenerated from man page /usr/share/man/man1/tpm2_policynvwritten.1.gz
complete -c tpm2_policynvwritten -s S -l session -d 'A session file from tpm2_startauthsession(1)[cq]s'
complete -c tpm2_policynvwritten -s L -l policy -d 'File to save the policy digest'
complete -c tpm2_policynvwritten -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_policynvwritten -s h -l help -d manpage
complete -c tpm2_policynvwritten -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policynvwritten -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policynvwritten -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policynvwritten -s Z -l enable-errata -d 'errata fixups'

