# tpm2_policypassword
# Autogenerated from man page /usr/share/man/man1/tpm2_policypassword.1.gz
complete -c tpm2_policypassword -s L -l policy -d 'File to save the compounded policy digest'
complete -c tpm2_policypassword -s S -l session -d 'The policy session file generated via the -S option to tpm2_startauthsession(…'
complete -c tpm2_policypassword -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_policypassword -s h -l help -d manpage
complete -c tpm2_policypassword -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_policypassword -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_policypassword -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_policypassword -s Z -l enable-errata -d 'errata fixups'

