# tpm2_hierarchycontrol
# Autogenerated from man page /usr/share/man/man1/tpm2_hierarchycontrol.1.gz
complete -c tpm2_hierarchycontrol -s C -l hierarchy
complete -c tpm2_hierarchycontrol -s P -l hierarchy-auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_hierarchycontrol -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_hierarchycontrol -s h -l help -d manpage
complete -c tpm2_hierarchycontrol -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_hierarchycontrol -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_hierarchycontrol -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_hierarchycontrol -s Z -l enable-errata -d 'errata fixups'

