# tpm2_nvdefine
# Autogenerated from man page /usr/share/man/man1/tpm2_nvdefine.1.gz
complete -c tpm2_nvdefine -s C -l hierarchy
complete -c tpm2_nvdefine -s s -l size -d 'Specifies the size of data area in bytes'
complete -c tpm2_nvdefine -s g -l hash-algorithm -d 'The hash algorithm used to compute the name of the Index and used for the aut…'
complete -c tpm2_nvdefine -s a -l attributes -d 'Specifies the attribute values for the nv region used when creating the entity'
complete -c tpm2_nvdefine -s P -l hierarchy-auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_nvdefine -s p -l index-auth -d 'Specifies the password of NV Index when created'
complete -c tpm2_nvdefine -s L -l policy -d 'Specifies the policy digest file for policy based authorizations'
complete -c tpm2_nvdefine -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_nvdefine -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_nvdefine -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_nvdefine -s h -l help -d manpage
complete -c tpm2_nvdefine -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_nvdefine -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_nvdefine -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_nvdefine -s Z -l enable-errata -d 'errata fixups'

