# tpm2_shutdown
# Autogenerated from man page /usr/share/man/man1/tpm2_shutdown.1.gz
complete -c tpm2_shutdown -s c -l clear -d 'Shutdown type sent will be TPM_SU_CLEAR instead of TPM2_SU_STATE'
complete -c tpm2_shutdown -s h -l help -d manpage
complete -c tpm2_shutdown -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_shutdown -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_shutdown -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_shutdown -s Z -l enable-errata -d 'errata fixups'

