# tpm2_gettime
# Autogenerated from man page /usr/share/man/man1/tpm2_gettime.1.gz
complete -c tpm2_gettime -s c -l key-context -d 'Context object pointing to the the key used for signing'
complete -c tpm2_gettime -s p -l auth_AUTH_ -d 'Optional authorization value to use the key specified by -c'
complete -c tpm2_gettime -s P -l endorse-auth_AUTH_ -d 'Optional authorization value for the endorsement hierarchy'
complete -c tpm2_gettime -s g -l hash-algorithm -d 'The hash algorithm used to digest the message'
complete -c tpm2_gettime -s s -l scheme -d 'The signing scheme used to sign the message.  Optional'
complete -c tpm2_gettime -s q -l qualification -d 'Optional, the policy qualifier data that the signer can choose to include in …'
complete -c tpm2_gettime -s o -l signature -d 'The signature file, records the signature structure'
complete -c tpm2_gettime -s f -l format -d 'Format selection for the signature output file'
complete -c tpm2_gettime -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_gettime -s h -l help -d manpage
complete -c tpm2_gettime -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_gettime -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_gettime -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_gettime -s Z -l enable-errata -d 'errata fixups'

