# tpm2_createprimary
# Autogenerated from man page /usr/share/man/man1/tpm2_createprimary.1.gz
complete -c tpm2_createprimary -s C -l hierarchy
complete -c tpm2_createprimary -s P -l hierarchy-auth -d 'The authorization value for the hierarchy specified with -C'
complete -c tpm2_createprimary -s p -l key-auth -d 'The authorization value for the primary object created'
complete -c tpm2_createprimary -s g -l hash-algorithm -d 'The hash algorithm to use for generating the objects name'
complete -c tpm2_createprimary -s G -l key-algorithm -d 'The algorithm type for the generated primary key'
complete -c tpm2_createprimary -s c -l key-context -d 'The file path to save the object context of the generated primary object'
complete -c tpm2_createprimary -s L -l policy -d 'HEX_STRING: An optional file input or hex string that contains the policy dig…'
complete -c tpm2_createprimary -s a -l attributes -d 'The object attributes, optional'
complete -c tpm2_createprimary -s u -l unique-data -d 'STDIN: An optional file input that contains the unique field of TPMT_PUBLIC i…'
complete -c tpm2_createprimary -l creation-data -d 'An optional file output that saves the creation data for certification'
complete -c tpm2_createprimary -l template-data -d 'An optional file output that saves the key template data (TPM2B_PUBLIC) to be…'
complete -c tpm2_createprimary -s t -l creation-ticket -d 'An optional file output that saves the creation ticket for certification'
complete -c tpm2_createprimary -s d -l creation-hash -d 'An optional file output that saves the creation hash for certification'
complete -c tpm2_createprimary -s q -l outside-info -d 'An optional file or hex string to add unique data to the creation data'
complete -c tpm2_createprimary -s l -l pcr-list -d 'The list of PCR banks and selected PCRs[cq] ids for each bank to be included …'
complete -c tpm2_createprimary -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_createprimary -s f -l format -d 'Format selection for the public key output file'
complete -c tpm2_createprimary -s o -l output -d 'The output file path, recording the public portion of the object'
complete -c tpm2_createprimary -s h -l help -d manpage
complete -c tpm2_createprimary -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_createprimary -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_createprimary -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_createprimary -s Z -l enable-errata -d 'errata fixups'

