# tpm2_nvsetbits
# Autogenerated from man page /usr/share/man/man1/tpm2_nvsetbits.1.gz
complete -c tpm2_nvsetbits -s C -l hierarchy
complete -c tpm2_nvsetbits -s P -l auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_nvsetbits -s i -l bits -d 'Specifies the bit value as a number to bitwise OR into the current value of t…'
complete -c tpm2_nvsetbits -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_nvsetbits -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_nvsetbits -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_nvsetbits -s n -l name -d 'The name of the NV index that must be provided when only calculating the cpHa…'
complete -c tpm2_nvsetbits -s h -l help -d manpage
complete -c tpm2_nvsetbits -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_nvsetbits -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_nvsetbits -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_nvsetbits -s Z -l enable-errata -d 'errata fixups'

