# tpm2_createak
# Autogenerated from man page /usr/share/man/man1/tpm2_createak.1.gz
complete -c tpm2_createak -s P -l eh-auth -d 'The authorization value for the endorsement hierarchy'
complete -c tpm2_createak -s p -l ak-auth -d 'The authorization value for the attestation key object created'
complete -c tpm2_createak -s C -l ek-context -d 'The endorsement key object'
complete -c tpm2_createak -s c -l ak-context -d 'The file path to save the object context of the attestation key'
complete -c tpm2_createak -s G -l key-algorithm
complete -c tpm2_createak -s g -l hash-algorithm -d 'Specifies the digest algorithm used for signing'
complete -c tpm2_createak -s s -l signing-algorithm -d 'The signing algorithm'
complete -c tpm2_createak -s u -l public -d 'The file to save the public portion of the attestation key'
complete -c tpm2_createak -s n -l ak-name -d 'The file to save the attestation key name, optional'
complete -c tpm2_createak -s r -l private -d 'The output file which contains the sensitive portion of the object, optional'
complete -c tpm2_createak -s f -l format -d 'Format selection for the public key output file'
complete -c tpm2_createak -s q -l ak-qualified-name -d 'The qualified name of the attestation key object'
complete -c tpm2_createak -s h -l help -d manpage
complete -c tpm2_createak -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_createak -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_createak -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_createak -s Z -l enable-errata -d 'errata fixups'

