# tpm2_nvwritelock
# Autogenerated from man page /usr/share/man/man1/tpm2_nvwritelock.1.gz
complete -c tpm2_nvwritelock -s C -l hierarchy
complete -c tpm2_nvwritelock -s P -l auth -d 'Specifies the authorization value for the hierarchy'
complete -c tpm2_nvwritelock -l global -d 'Lock all NV indices with attribute TPMA_NV_GLOBALLOCK'
complete -c tpm2_nvwritelock -l cphash -d 'File path to record the hash of the command parameters'
complete -c tpm2_nvwritelock -l rphash -d 'File path to record the hash of the response parameters'
complete -c tpm2_nvwritelock -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_nvwritelock -s n -l name -d 'The name of the NV index that must be provided when only calculating the cpHa…'
complete -c tpm2_nvwritelock -s h -l help -d manpage
complete -c tpm2_nvwritelock -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_nvwritelock -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_nvwritelock -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_nvwritelock -s Z -l enable-errata -d 'errata fixups'

