# tpm2_getpolicydigest
# Autogenerated from man page /usr/share/man/man1/tpm2_getpolicydigest.1.gz
complete -c tpm2_getpolicydigest -s o -l output -d 'Specifies the filename to output the raw bytes to'
complete -c tpm2_getpolicydigest -l hex -d 'Convert the output data to hex format without a leading [lq]0x[rq]'
complete -c tpm2_getpolicydigest -s S -l session -d 'The session created using tpm2_startauthsession'
complete -c tpm2_getpolicydigest -s h -l help -d manpage
complete -c tpm2_getpolicydigest -s v -l version -d 'this tool, supported tctis and exit.  [bu] 2'
complete -c tpm2_getpolicydigest -s V -l verbose -d 'tool prints to the console during its execution'
complete -c tpm2_getpolicydigest -s Q -l quiet -d 'stdout.  [bu] 2'
complete -c tpm2_getpolicydigest -s Z -l enable-errata -d 'errata fixups'

