# tss2_delete
# Autogenerated from man page /usr/share/man/man1/tss2_delete.1.gz
complete -c tss2_delete -s p -l path -d 'The path to the entity to delete'
complete -c tss2_delete -s h -l help -d manpage
complete -c tss2_delete -s v -l version -d 'this tool, supported tctis and exit'

