# tss2_nvsetbits
# Autogenerated from man page /usr/share/man/man1/tss2_nvsetbits.1.gz
complete -c tss2_nvsetbits -s i -l bitmap -d 'A mask indicating which bits to set in the NV space'
complete -c tss2_nvsetbits -s p -l nvPath -d 'Identifies the NV space to write'
complete -c tss2_nvsetbits -s h -l help -d manpage
complete -c tss2_nvsetbits -s v -l version -d 'this tool, supported tctis and exit'

