# tss2_setdescription
# Autogenerated from man page /usr/share/man/man1/tss2_setdescription.1.gz
complete -c tss2_setdescription -s i -l description -d 'The data to be stored as description for the object.  Optional parameter'
complete -c tss2_setdescription -s p -l path -d 'The path of the object for which the description will be stored'
complete -c tss2_setdescription -s h -l help -d manpage
complete -c tss2_setdescription -s v -l version -d 'this tool, supported tctis and exit'

