# tss2_getcertificate
# Autogenerated from man page /usr/share/man/man1/tss2_getcertificate.1.gz
complete -c tss2_getcertificate -s f -l force -d 'Force overwriting the output file'
complete -c tss2_getcertificate -s p -l path -d 'The entity whose certificate is requested'
complete -c tss2_getcertificate -s o -l x509certData
complete -c tss2_getcertificate -s h -l help -d manpage
complete -c tss2_getcertificate -s v -l version -d 'this tool, supported tctis and exit'

