# tss2_getplatformcertificates
# Autogenerated from man page /usr/share/man/man1/tss2_getplatformcertificates.1.gz
complete -c tss2_getplatformcertificates -s f -l force -d 'Force overwriting the output file'
complete -c tss2_getplatformcertificates -s o -l certificates
complete -c tss2_getplatformcertificates -s h -l help -d manpage
complete -c tss2_getplatformcertificates -s v -l version -d 'this tool, supported tctis and exit'

