# tss2_quote
# Autogenerated from man page /usr/share/man/man1/tss2_quote.1.gz
complete -c tss2_quote -s x -l pcrList -d 'An array holding the PCR indices to quote against'
complete -c tss2_quote -s Q -l qualifyingData
complete -c tss2_quote -s l -l pcrLog -d '(for stdout): Returns the PCR log for the chosen PCR.  Optional parameter'
complete -c tss2_quote -s f -l force -d 'Force overwriting the output file'
complete -c tss2_quote -s p -l keyPath -d 'Identifies the signing key'
complete -c tss2_quote -s q -l quoteInfo
complete -c tss2_quote -s o -l signature
complete -c tss2_quote -s c -l certificate
complete -c tss2_quote -s h -l help -d manpage
complete -c tss2_quote -s v -l version -d 'this tool, supported tctis and exit'

