# tss2_pcrextend
# Autogenerated from man page /usr/share/man/man1/tss2_pcrextend.1.gz
complete -c tss2_pcrextend -s x -l pcr
complete -c tss2_pcrextend -s i -l data -d '(for stdin): The event data to be extended'
complete -c tss2_pcrextend -s l -l logData -d '(for stdin): Contains a JSON representation of data to be written to the PCR[…'
complete -c tss2_pcrextend -s h -l help -d manpage
complete -c tss2_pcrextend -s v -l version -d 'this tool, supported tctis and exit'

