# tss2_decrypt
# Autogenerated from man page /usr/share/man/man1/tss2_decrypt.1.gz
complete -c tss2_decrypt -s p -l keyPath -d 'Identifies the decryption key'
complete -c tss2_decrypt -s i -l cipherText
complete -c tss2_decrypt -s f -l force -d 'Force Overwriting the output file'
complete -c tss2_decrypt -s o -l plainText
complete -c tss2_decrypt -s h -l help -d manpage
complete -c tss2_decrypt -s v -l version -d 'this tool, supported tctis and exit'

