# tss2_verifysignature
# Autogenerated from man page /usr/share/man/man1/tss2_verifysignature.1.gz
complete -c tss2_verifysignature -s d -l digest -d '(for stdin): The data that was signed, already hashed according to the crypto…'
complete -c tss2_verifysignature -s p -l keyPath -d 'Path to the verification public key'
complete -c tss2_verifysignature -s i -l signature
complete -c tss2_verifysignature -s h -l help -d manpage
complete -c tss2_verifysignature -s v -l version -d 'this tool, supported tctis and exit'

