# tss2_encrypt
# Autogenerated from man page /usr/share/man/man1/tss2_encrypt.1.gz
complete -c tss2_encrypt -s p -l keyPath -d 'Identifies the encryption key'
complete -c tss2_encrypt -s f -l force -d 'Force overwriting the output file'
complete -c tss2_encrypt -s i -l plainText
complete -c tss2_encrypt -s o -l cipherText
complete -c tss2_encrypt -s h -l help -d manpage
complete -c tss2_encrypt -s v -l version -d 'this tool, supported tctis and exit'

