# tss2_getrandom
# Autogenerated from man page /usr/share/man/man1/tss2_getrandom.1.gz
complete -c tss2_getrandom -s n -l numBytes -d 'The number of bytes requested by the caller'
complete -c tss2_getrandom -s f -l force -d 'Force overwriting the output file'
complete -c tss2_getrandom -s o -l data -d '(for stdout): The returned random bytes'
complete -c tss2_getrandom -l hex -d 'Convert the output data to hex format without a leading [lq]0x[rq]'
complete -c tss2_getrandom -s h -l help -d manpage
complete -c tss2_getrandom -s v -l version -d 'this tool, supported tctis and exit'

