# tss2_nvwrite
# Autogenerated from man page /usr/share/man/man1/tss2_nvwrite.1.gz
complete -c tss2_nvwrite -s i -l data -d '(for stdin): The data to write to the NV space'
complete -c tss2_nvwrite -s p -l nvPath -d 'Identifies the NV space to write to'
complete -c tss2_nvwrite -s h -l help -d manpage
complete -c tss2_nvwrite -s v -l version -d 'this tool, supported tctis and exit'

