# tss2_getdescription
# Autogenerated from man page /usr/share/man/man1/tss2_getdescription.1.gz
complete -c tss2_getdescription -s f -l force -d 'Force overwriting the output file'
complete -c tss2_getdescription -s p -l path -d 'The path of the object for which the description will be loaded'
complete -c tss2_getdescription -s o -l description
complete -c tss2_getdescription -s h -l help -d manpage
complete -c tss2_getdescription -s v -l version -d 'this tool, supported tctis and exit'

