# tss2_createseal
# Autogenerated from man page /usr/share/man/man1/tss2_createseal.1.gz
complete -c tss2_createseal -s p -l path -d 'The path to the new key'
complete -c tss2_createseal -s t -l type -d 'Identifies the intended usage.  Optional parameter'
complete -c tss2_createseal -s P -l policyPath -d 'Identifies the policy to be associated with the new key.  Optional parameter'
complete -c tss2_createseal -s a -l authValue -d 'The new UTF-8 password.  Optional parameter'
complete -c tss2_createseal -s i -l data -d '(for stdin): The data to be sealed by the TPM.  Optional parameter'
complete -c tss2_createseal -s s -l size -d 'Determines the number of random bytes the TPM should generate and seal'
complete -c tss2_createseal -s h -l help -d manpage
complete -c tss2_createseal -s v -l version -d 'this tool, supported tctis and exit'

