# tss2_nvread
# Autogenerated from man page /usr/share/man/man1/tss2_nvread.1.gz
complete -c tss2_nvread -s f -l force -d 'Force overwriting the output file'
complete -c tss2_nvread -s o -l data -d '(for stdout): Returns the value read from the NV space'
complete -c tss2_nvread -s p -l nvPath -d 'Identifies the NV space to read'
complete -c tss2_nvread -s l -l logData -d '(for stdout): Returns the JSON encoded log, if the NV index is of type [lq]ex…'
complete -c tss2_nvread -s h -l help -d manpage
complete -c tss2_nvread -s v -l version -d 'this tool, supported tctis and exit'

