# tss2_import
# Autogenerated from man page /usr/share/man/man1/tss2_import.1.gz
complete -c tss2_import -s p -l path -d 'The path of the new object'
complete -c tss2_import -s i -l importData
complete -c tss2_import -s h -l help -d manpage
complete -c tss2_import -s v -l version -d 'this tool, supported tctis and exit'

