# tss2_provision
# Autogenerated from man page /usr/share/man/man1/tss2_provision.1.gz
complete -c tss2_provision -s E -l authValueEh -d 'authorization value for the privacy admin, i. e.  the endorsement hierarchy'
complete -c tss2_provision -s S -l authValueSh -d 'authorization value for the owner, i. e.  the storage hierarchy'
complete -c tss2_provision -s L -l authValueLockout -d 'authorization value for the lockout authorization.  Optional parameter'
complete -c tss2_provision -s h -l help -d manpage
complete -c tss2_provision -s v -l version -d 'this tool, supported tctis and exit.  EXAMPLE tss2_provision RETURNS'

