# tss2_setappdata
# Autogenerated from man page /usr/share/man/man1/tss2_setappdata.1.gz
complete -c tss2_setappdata -s p -l path -d 'Path of the object for which the appData will be stored'
complete -c tss2_setappdata -s i -l appData -d '(for stdin): The data to be stored.  Optional parameter'
complete -c tss2_setappdata -s h -l help -d manpage
complete -c tss2_setappdata -s v -l version -d 'this tool, supported tctis and exit'

