# tss2_writeauthorizenv
# Autogenerated from man page /usr/share/man/man1/tss2_writeauthorizenv.1.gz
complete -c tss2_writeauthorizenv -s p -l nvPath -d 'The path of the NV index'
complete -c tss2_writeauthorizenv -s P -l policyPath -d 'The path of the new policy'
complete -c tss2_writeauthorizenv -s h -l help -d manpage
complete -c tss2_writeauthorizenv -s v -l version -d 'this tool, supported tctis and exit'

