# tss2_createkey
# Autogenerated from man page /usr/share/man/man1/tss2_createkey.1.gz
complete -c tss2_createkey -s p -l path -d 'The path to the new key'
complete -c tss2_createkey -s t -l type -d 'Identifies the intended usage.  Optional parameter'
complete -c tss2_createkey -s P -l policyPath -d 'The policy to be associated with the new key.  Optional parameter'
complete -c tss2_createkey -s a -l authValue -d 'The new UTF-8 password.  Optional parameter'
complete -c tss2_createkey -s h -l help -d manpage
complete -c tss2_createkey -s v -l version -d 'this tool, supported tctis and exit'

