# tss2_exportkey
# Autogenerated from man page /usr/share/man/man1/tss2_exportkey.1.gz
complete -c tss2_exportkey -s e -l pathToPublicKeyOfNewParent -d 'The path to the public key of the new parent'
complete -c tss2_exportkey -s f -l force -d 'Force overwriting the output file'
complete -c tss2_exportkey -s o -l exportedData
complete -c tss2_exportkey -s p -l pathOfKeyToDuplicate -d 'The path to the root of the subtree to export'
complete -c tss2_exportkey -s h -l help -d manpage
complete -c tss2_exportkey -s v -l version -d 'this tool, supported tctis and exit'

