# tss2_nvextend
# Autogenerated from man page /usr/share/man/man1/tss2_nvextend.1.gz
complete -c tss2_nvextend -s i -l data -d '(for stdin): The data to be extended into the NV space'
complete -c tss2_nvextend -s p -l nvPath -d 'Identifies the NV space to write'
complete -c tss2_nvextend -s l -l logData -d '(for stdin): A JSON representation of data to be written to the PCR[cq]s even…'
complete -c tss2_nvextend -s h -l help -d manpage
complete -c tss2_nvextend -s v -l version -d 'this tool, supported tctis and exit'

