# tss2_getinfo
# Autogenerated from man page /usr/share/man/man1/tss2_getinfo.1.gz
complete -c tss2_getinfo -s f -l force -d 'Force overwriting the output file'
complete -c tss2_getinfo -s o -l info -d '(for stdout): Returns the FAPI and TPM information'
complete -c tss2_getinfo -s h -l help -d manpage
complete -c tss2_getinfo -s v -l version -d 'this tool, supported tctis and exit.  EXAMPLE tss2_getinfo --info=info'

