# tss2_list
# Autogenerated from man page /usr/share/man/man1/tss2_list.1.gz
complete -c tss2_list -s f -l force -d 'Force overwriting the output file'
complete -c tss2_list -s p -l searchPath -d 'The path identifying the root of the search.  Optional parameter'
complete -c tss2_list -s o -l pathList -d '(for stdout): Returns the colon-separated list of paths.  Optional parameter'
complete -c tss2_list -s h -l help -d manpage
complete -c tss2_list -s v -l version -d 'this tool, supported tctis and exit'

