# tss2_getappdata
# Autogenerated from man page /usr/share/man/man1/tss2_getappdata.1.gz
complete -c tss2_getappdata -s f -l force -d 'Force overwriting the output file'
complete -c tss2_getappdata -s p -l path -d 'Path of the object for which the application data will be loaded'
complete -c tss2_getappdata -s o -l appData -d '(for stdout): Returns a copy of the stored data.  Optional parameter'
complete -c tss2_getappdata -s h -l help -d manpage
complete -c tss2_getappdata -s v -l version -d 'this tool, supported tctis and exit'

