# tss2_pcrread
# Autogenerated from man page /usr/share/man/man1/tss2_pcrread.1.gz
complete -c tss2_pcrread -s o -l pcrValue -d '(for stdout): Returns PCR digest.  Optional parameter'
complete -c tss2_pcrread -s x -l pcrIndex -d 'Identifies the PCR to read'
complete -c tss2_pcrread -s f -l force -d 'Force overwriting the output files'
complete -c tss2_pcrread -s l -l pcrLog -d '(for stdout): Returns the PCR log for that PCR.  Optional parameter'
complete -c tss2_pcrread -s h -l help -d manpage
complete -c tss2_pcrread -s v -l version -d 'this tool, supported tctis and exit'

