# tss2_authorizepolicy
# Autogenerated from man page /usr/share/man/man1/tss2_authorizepolicy.1.gz
complete -c tss2_authorizepolicy -s P -l policyPath -d 'new policy.  A policyPath is composed of two elements, separated by [lq]/[rq]'
complete -c tss2_authorizepolicy -s p -l keyPath -d 'signing key.  [bu] 2'
complete -c tss2_authorizepolicy -s r -l policyRef
complete -c tss2_authorizepolicy -s h -l help -d manpage
complete -c tss2_authorizepolicy -s v -l version -d 'this tool, supported tctis and exit'

