# tss2_exportpolicy
# Autogenerated from man page /usr/share/man/man1/tss2_exportpolicy.1.gz
complete -c tss2_exportpolicy -s f -l force -d 'Force overwriting the output file'
complete -c tss2_exportpolicy -s o -l jsonPolicy
complete -c tss2_exportpolicy -s p -l path -d 'The path of the key'
complete -c tss2_exportpolicy -s h -l help -d manpage
complete -c tss2_exportpolicy -s v -l version -d 'this tool, supported tctis and exit'

