# tss2_setcertificate
# Autogenerated from man page /usr/share/man/man1/tss2_setcertificate.1.gz
complete -c tss2_setcertificate -s p -l path -d 'Identifies the entity to be associated with the certificate'
complete -c tss2_setcertificate -s i -l x509certData
complete -c tss2_setcertificate -s h -l help -d manpage
complete -c tss2_setcertificate -s v -l version -d 'this tool, supported tctis and exit'

