# tss2_unseal
# Autogenerated from man page /usr/share/man/man1/tss2_unseal.1.gz
complete -c tss2_unseal -s f -l force -d 'Force overwriting the output file'
complete -c tss2_unseal -s p -l path -d 'Path of the object for which the blobs will be returned'
complete -c tss2_unseal -s o -l data -d '(for stdout): The decrypted data after unsealing.  Optional parameter'
complete -c tss2_unseal -s h -l help -d manpage
complete -c tss2_unseal -s v -l version -d 'this tool, supported tctis and exit'

