# tss2_verifyquote
# Autogenerated from man page /usr/share/man/man1/tss2_verifyquote.1.gz
complete -c tss2_verifyquote -s Q -l qualifyingData
complete -c tss2_verifyquote -s l -l pcrLog -d '(for stdin): Returns the PCR event log for the chosen PCR'
complete -c tss2_verifyquote -s q -l quoteInfo
complete -c tss2_verifyquote -s k -l publicKeyPath -d 'Identifies the signing key.  MAY be a path to the public key hierarchy /ext'
complete -c tss2_verifyquote -s i -l signature
complete -c tss2_verifyquote -s h -l help -d manpage
complete -c tss2_verifyquote -s v -l version -d 'this tool, supported tctis and exit'

