# tss2_gettpm2object
# Autogenerated from man page /usr/share/man/man1/tss2_gettpm2object.1.gz
complete -c tss2_gettpm2object -s f -l force -d 'Force overwriting the output file'
complete -c tss2_gettpm2object -s p -l path -d 'Path of the object for which the application data will be loaded'
complete -c tss2_gettpm2object -s c -l context -d '(for stdout): The returned key context or handle'
complete -c tss2_gettpm2object -s h -l help -d manpage
complete -c tss2_gettpm2object -s v -l version -d 'this tool, supported tctis and exit'

