# tss2_createnv
# Autogenerated from man page /usr/share/man/man1/tss2_createnv.1.gz
complete -c tss2_createnv -s p -l path -d 'Path of the new NV space'
complete -c tss2_createnv -s t -l type -d 'Identifies the intended usage.  Optional parameter'
complete -c tss2_createnv -s s -l size -d 'The size in bytes of the NV index to be created'
complete -c tss2_createnv -s P -l policyPath -d 'Identifies the policy to be associated with the new NV space'
complete -c tss2_createnv -s a -l authValue -d 'The new UTF-8 password.  Optional parameter'
complete -c tss2_createnv -s h -l help -d manpage
complete -c tss2_createnv -s v -l version -d 'this tool, supported tctis and exit'

