# update-crypto-policies
# Autogenerated from man page /usr/share/man/man8/update-crypto-policies.8.gz
complete -c update-crypto-policies -l set -d 'oc o 2. 3'
complete -c update-crypto-policies -l show -d 'oc o 2. 3'
complete -c update-crypto-policies -l is-applied -d 'oc o 2. 3'
complete -c update-crypto-policies -l check
complete -c update-crypto-policies -l no-reload

