# yum-changelog
# Autogenerated from man page /usr/share/man/man1/yum-changelog.1.gz
complete -c yum-changelog -l since -d 'Show only changelog entries since <date>'
complete -c yum-changelog -l count -d 'Show maximum of <number> changelog entries per package'
complete -c yum-changelog -l upgrades -d 'Show only new changelog entries for packages, that provide an upgrade for som…'

